
// Generated by Cadence Genus(TM) Synthesis Solution 23.16-s067_1
// Generated on: Mar 11 2026 19:56:05 IST (Mar 11 2026 14:26:05 UTC)

// Verification Directory fv/sync_fifo 

module sync_fifo(clk, rstn, wr_en, rd_en, din, dout, empty, full);
  input clk, rstn, wr_en, rd_en;
  input [15:0] din;
  output [15:0] dout;
  output empty, full;
  wire clk, rstn, wr_en, rd_en;
  wire [15:0] din;
  wire [15:0] dout;
  wire empty, full;
  wire [15:0] \fifo_mem[1] ;
  wire [15:0] \fifo_mem[2] ;
  wire [15:0] \fifo_mem[0] ;
  wire [15:0] \fifo_mem[4] ;
  wire [15:0] \fifo_mem[3] ;
  wire [15:0] \fifo_mem[7] ;
  wire [15:0] \fifo_mem[5] ;
  wire [15:0] \fifo_mem[6] ;
  wire [2:0] wptr;
  wire [2:0] rptr;
  wire n_4, n_5, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_156, n_157, n_158, n_159;
  wire n_160;
  DFFRHQX1LVT \dout_reg[0] (.RN (rstn), .CK (clk), .D (n_145), .Q
       (dout[0]));
  DFFRHQX1LVT \dout_reg[1] (.RN (rstn), .CK (clk), .D (n_140), .Q
       (dout[1]));
  DFFRHQX1LVT \dout_reg[6] (.RN (rstn), .CK (clk), .D (n_141), .Q
       (dout[6]));
  DFFRHQX1LVT \dout_reg[7] (.RN (rstn), .CK (clk), .D (n_150), .Q
       (dout[7]));
  DFFRHQX1LVT \dout_reg[8] (.RN (rstn), .CK (clk), .D (n_146), .Q
       (dout[8]));
  DFFRHQX1LVT \dout_reg[2] (.RN (rstn), .CK (clk), .D (n_143), .Q
       (dout[2]));
  DFFRHQX1LVT \dout_reg[9] (.RN (rstn), .CK (clk), .D (n_142), .Q
       (dout[9]));
  DFFRHQX1LVT \dout_reg[3] (.RN (rstn), .CK (clk), .D (n_139), .Q
       (dout[3]));
  DFFRHQX1LVT \dout_reg[10] (.RN (rstn), .CK (clk), .D (n_138), .Q
       (dout[10]));
  DFFRHQX1LVT \dout_reg[4] (.RN (rstn), .CK (clk), .D (n_137), .Q
       (dout[4]));
  DFFRHQX1LVT \dout_reg[11] (.RN (rstn), .CK (clk), .D (n_136), .Q
       (dout[11]));
  DFFRHQX1LVT \dout_reg[12] (.RN (rstn), .CK (clk), .D (n_149), .Q
       (dout[12]));
  DFFRHQX1LVT \dout_reg[5] (.RN (rstn), .CK (clk), .D (n_148), .Q
       (dout[5]));
  DFFRHQX1LVT \dout_reg[13] (.RN (rstn), .CK (clk), .D (n_151), .Q
       (dout[13]));
  DFFRHQX1LVT \dout_reg[14] (.RN (rstn), .CK (clk), .D (n_147), .Q
       (dout[14]));
  DFFRHQX1LVT \dout_reg[15] (.RN (rstn), .CK (clk), .D (n_144), .Q
       (dout[15]));
  NAND2X1LVT g5078__2398(.A (n_51), .B (n_134), .Y (n_151));
  NAND2X1LVT g5068__5107(.A (n_52), .B (n_115), .Y (n_150));
  NAND2X1LVT g5076__6260(.A (n_50), .B (n_119), .Y (n_149));
  NAND2X1LVT g5077__4319(.A (n_47), .B (n_129), .Y (n_148));
  NAND2X1LVT g5075__8428(.A (n_48), .B (n_128), .Y (n_147));
  NAND2X1LVT g5069__5526(.A (n_43), .B (n_122), .Y (n_146));
  NAND2X1LVT g5079__6783(.A (n_44), .B (n_124), .Y (n_145));
  NAND2X1LVT g5080__3680(.A (n_35), .B (n_126), .Y (n_144));
  NAND2X1LVT g5071__1617(.A (n_42), .B (n_120), .Y (n_143));
  NAND2X1LVT g5070__2802(.A (n_39), .B (n_116), .Y (n_142));
  NAND2X1LVT g5081__1705(.A (n_40), .B (n_125), .Y (n_141));
  NAND2X1LVT g5082__5122(.A (n_49), .B (n_130), .Y (n_140));
  NAND2X1LVT g5067__8246(.A (n_38), .B (n_135), .Y (n_139));
  NAND2X1LVT g5072__7098(.A (n_41), .B (n_117), .Y (n_138));
  NAND2X1LVT g5073__6131(.A (n_46), .B (n_132), .Y (n_137));
  NAND2X1LVT g5074__1881(.A (n_36), .B (n_118), .Y (n_136));
  AOI221X1LVT g5119__5115(.A0 (dout[3]), .A1 (n_133), .B0
       (\fifo_mem[1] [3]), .B1 (n_123), .C0 (n_104), .Y (n_135));
  AOI221X1LVT g5120__7482(.A0 (dout[13]), .A1 (n_133), .B0
       (\fifo_mem[2] [13]), .B1 (n_131), .C0 (n_99), .Y (n_134));
  AOI221X1LVT g5121__4733(.A0 (dout[4]), .A1 (n_133), .B0
       (\fifo_mem[2] [4]), .B1 (n_131), .C0 (n_97), .Y (n_132));
  AOI221X1LVT g5122__6161(.A0 (\fifo_mem[2] [1]), .A1 (n_131), .B0
       (\fifo_mem[0] [1]), .B1 (n_127), .C0 (n_96), .Y (n_130));
  AOI221X1LVT g5107__9315(.A0 (dout[5]), .A1 (n_133), .B0
       (\fifo_mem[2] [5]), .B1 (n_131), .C0 (n_98), .Y (n_129));
  AOI221X1LVT g5108__9945(.A0 (\fifo_mem[2] [14]), .A1 (n_131), .B0
       (\fifo_mem[0] [14]), .B1 (n_127), .C0 (n_101), .Y (n_128));
  AOI221X1LVT g5109__2883(.A0 (\fifo_mem[2] [15]), .A1 (n_131), .B0
       (\fifo_mem[0] [15]), .B1 (n_127), .C0 (n_95), .Y (n_126));
  AOI221X1LVT g5110__2346(.A0 (\fifo_mem[2] [6]), .A1 (n_131), .B0
       (\fifo_mem[0] [6]), .B1 (n_127), .C0 (n_110), .Y (n_125));
  AOI221X1LVT g5111__1666(.A0 (\fifo_mem[1] [0]), .A1 (n_123), .B0
       (\fifo_mem[0] [0]), .B1 (n_127), .C0 (n_106), .Y (n_124));
  AOI221X1LVT g5118__7410(.A0 (dout[8]), .A1 (n_133), .B0
       (\fifo_mem[2] [8]), .B1 (n_131), .C0 (n_107), .Y (n_122));
  SDFFQX1LVT \fifo_mem_reg[0][2] (.CK (clk), .D (\fifo_mem[0] [2]), .SI
       (din[2]), .SE (n_121), .Q (\fifo_mem[0] [2]));
  SDFFQX1LVT \fifo_mem_reg[0][6] (.CK (clk), .D (\fifo_mem[0] [6]), .SI
       (din[6]), .SE (n_121), .Q (\fifo_mem[0] [6]));
  SDFFQX1LVT \fifo_mem_reg[0][3] (.CK (clk), .D (\fifo_mem[0] [3]), .SI
       (din[3]), .SE (n_121), .Q (\fifo_mem[0] [3]));
  SDFFQX1LVT \fifo_mem_reg[0][4] (.CK (clk), .D (\fifo_mem[0] [4]), .SI
       (din[4]), .SE (n_121), .Q (\fifo_mem[0] [4]));
  SDFFQX1LVT \fifo_mem_reg[0][5] (.CK (clk), .D (\fifo_mem[0] [5]), .SI
       (din[5]), .SE (n_121), .Q (\fifo_mem[0] [5]));
  SDFFQX1LVT \fifo_mem_reg[0][1] (.CK (clk), .D (\fifo_mem[0] [1]), .SI
       (din[1]), .SE (n_121), .Q (\fifo_mem[0] [1]));
  AOI221X1LVT g5117__6417(.A0 (dout[2]), .A1 (n_133), .B0
       (\fifo_mem[2] [2]), .B1 (n_131), .C0 (n_108), .Y (n_120));
  AOI221X1LVT g5116__5477(.A0 (\fifo_mem[1] [12]), .A1 (n_123), .B0
       (\fifo_mem[0] [12]), .B1 (n_127), .C0 (n_100), .Y (n_119));
  AOI221X1LVT g5115__2398(.A0 (\fifo_mem[1] [11]), .A1 (n_123), .B0
       (\fifo_mem[0] [11]), .B1 (n_127), .C0 (n_102), .Y (n_118));
  AOI221X1LVT g5114__5107(.A0 (\fifo_mem[1] [10]), .A1 (n_123), .B0
       (\fifo_mem[0] [10]), .B1 (n_127), .C0 (n_103), .Y (n_117));
  AOI221X1LVT g5113__6260(.A0 (\fifo_mem[1] [9]), .A1 (n_123), .B0
       (\fifo_mem[0] [9]), .B1 (n_127), .C0 (n_109), .Y (n_116));
  AOI221X1LVT g5112__4319(.A0 (\fifo_mem[1] [7]), .A1 (n_123), .B0
       (\fifo_mem[0] [7]), .B1 (n_127), .C0 (n_105), .Y (n_115));
  SDFFQX1LVT \fifo_mem_reg[0][14] (.CK (clk), .D (\fifo_mem[0] [14]),
       .SI (din[14]), .SE (n_121), .Q (\fifo_mem[0] [14]));
  SDFFQX1LVT \fifo_mem_reg[0][15] (.CK (clk), .D (\fifo_mem[0] [15]),
       .SI (din[15]), .SE (n_121), .Q (\fifo_mem[0] [15]));
  SDFFQX1LVT \fifo_mem_reg[0][0] (.CK (clk), .D (\fifo_mem[0] [0]), .SI
       (din[0]), .SE (n_121), .Q (\fifo_mem[0] [0]));
  SDFFQX1LVT \fifo_mem_reg[0][13] (.CK (clk), .D (\fifo_mem[0] [13]),
       .SI (din[13]), .SE (n_121), .Q (\fifo_mem[0] [13]));
  SDFFQX1LVT \fifo_mem_reg[0][12] (.CK (clk), .D (\fifo_mem[0] [12]),
       .SI (din[12]), .SE (n_121), .Q (\fifo_mem[0] [12]));
  SDFFQX1LVT \fifo_mem_reg[0][11] (.CK (clk), .D (\fifo_mem[0] [11]),
       .SI (din[11]), .SE (n_121), .Q (\fifo_mem[0] [11]));
  SDFFQX1LVT \fifo_mem_reg[0][10] (.CK (clk), .D (\fifo_mem[0] [10]),
       .SI (din[10]), .SE (n_121), .Q (\fifo_mem[0] [10]));
  SDFFQX1LVT \fifo_mem_reg[0][9] (.CK (clk), .D (\fifo_mem[0] [9]), .SI
       (din[9]), .SE (n_121), .Q (\fifo_mem[0] [9]));
  SDFFQX1LVT \fifo_mem_reg[0][7] (.CK (clk), .D (\fifo_mem[0] [7]), .SI
       (din[7]), .SE (n_121), .Q (\fifo_mem[0] [7]));
  SDFFQX1LVT \fifo_mem_reg[0][8] (.CK (clk), .D (\fifo_mem[0] [8]), .SI
       (din[8]), .SE (n_121), .Q (\fifo_mem[0] [8]));
  SDFFQX1LVT \fifo_mem_reg[4][13] (.CK (clk), .D (\fifo_mem[4] [13]),
       .SI (din[13]), .SE (n_114), .Q (\fifo_mem[4] [13]));
  SDFFQX1LVT \fifo_mem_reg[3][15] (.CK (clk), .D (\fifo_mem[3] [15]),
       .SI (din[15]), .SE (n_157), .Q (\fifo_mem[3] [15]));
  SDFFQX1LVT \fifo_mem_reg[4][14] (.CK (clk), .D (\fifo_mem[4] [14]),
       .SI (din[14]), .SE (n_114), .Q (\fifo_mem[4] [14]));
  SDFFQX1LVT \fifo_mem_reg[4][0] (.CK (clk), .D (\fifo_mem[4] [0]), .SI
       (din[0]), .SE (n_114), .Q (\fifo_mem[4] [0]));
  SDFFQX1LVT \fifo_mem_reg[4][1] (.CK (clk), .D (\fifo_mem[4] [1]), .SI
       (din[1]), .SE (n_114), .Q (\fifo_mem[4] [1]));
  SDFFQX1LVT \fifo_mem_reg[4][2] (.CK (clk), .D (\fifo_mem[4] [2]), .SI
       (din[2]), .SE (n_114), .Q (\fifo_mem[4] [2]));
  SDFFQX1LVT \fifo_mem_reg[4][4] (.CK (clk), .D (\fifo_mem[4] [4]), .SI
       (din[4]), .SE (n_114), .Q (\fifo_mem[4] [4]));
  SDFFQX1LVT \fifo_mem_reg[4][5] (.CK (clk), .D (\fifo_mem[4] [5]), .SI
       (din[5]), .SE (n_114), .Q (\fifo_mem[4] [5]));
  SDFFQX1LVT \fifo_mem_reg[4][6] (.CK (clk), .D (\fifo_mem[4] [6]), .SI
       (din[6]), .SE (n_114), .Q (\fifo_mem[4] [6]));
  SDFFQX1LVT \fifo_mem_reg[4][7] (.CK (clk), .D (\fifo_mem[4] [7]), .SI
       (din[7]), .SE (n_114), .Q (\fifo_mem[4] [7]));
  SDFFQX1LVT \fifo_mem_reg[4][8] (.CK (clk), .D (\fifo_mem[4] [8]), .SI
       (din[8]), .SE (n_114), .Q (\fifo_mem[4] [8]));
  SDFFQX1LVT \fifo_mem_reg[4][9] (.CK (clk), .D (\fifo_mem[4] [9]), .SI
       (din[9]), .SE (n_114), .Q (\fifo_mem[4] [9]));
  SDFFQX1LVT \fifo_mem_reg[4][10] (.CK (clk), .D (\fifo_mem[4] [10]),
       .SI (din[10]), .SE (n_114), .Q (\fifo_mem[4] [10]));
  SDFFQX1LVT \fifo_mem_reg[4][3] (.CK (clk), .D (\fifo_mem[4] [3]), .SI
       (din[3]), .SE (n_114), .Q (\fifo_mem[4] [3]));
  SDFFQX1LVT \fifo_mem_reg[4][12] (.CK (clk), .D (\fifo_mem[4] [12]),
       .SI (din[12]), .SE (n_114), .Q (\fifo_mem[4] [12]));
  SDFFQX1LVT \fifo_mem_reg[3][11] (.CK (clk), .D (\fifo_mem[3] [11]),
       .SI (din[11]), .SE (n_157), .Q (\fifo_mem[3] [11]));
  SDFFQX1LVT \fifo_mem_reg[3][7] (.CK (clk), .D (\fifo_mem[3] [7]), .SI
       (din[7]), .SE (n_157), .Q (\fifo_mem[3] [7]));
  SDFFQX1LVT \fifo_mem_reg[4][15] (.CK (clk), .D (\fifo_mem[4] [15]),
       .SI (din[15]), .SE (n_114), .Q (\fifo_mem[4] [15]));
  SDFFQX1LVT \fifo_mem_reg[3][0] (.CK (clk), .D (\fifo_mem[3] [0]), .SI
       (din[0]), .SE (n_157), .Q (\fifo_mem[3] [0]));
  SDFFQX1LVT \fifo_mem_reg[3][1] (.CK (clk), .D (\fifo_mem[3] [1]), .SI
       (din[1]), .SE (n_157), .Q (\fifo_mem[3] [1]));
  SDFFQX1LVT \fifo_mem_reg[3][2] (.CK (clk), .D (\fifo_mem[3] [2]), .SI
       (din[2]), .SE (n_157), .Q (\fifo_mem[3] [2]));
  SDFFQX1LVT \fifo_mem_reg[3][3] (.CK (clk), .D (\fifo_mem[3] [3]), .SI
       (din[3]), .SE (n_157), .Q (\fifo_mem[3] [3]));
  SDFFQX1LVT \fifo_mem_reg[3][4] (.CK (clk), .D (\fifo_mem[3] [4]), .SI
       (din[4]), .SE (n_157), .Q (\fifo_mem[3] [4]));
  SDFFQX1LVT \fifo_mem_reg[3][5] (.CK (clk), .D (\fifo_mem[3] [5]), .SI
       (din[5]), .SE (n_157), .Q (\fifo_mem[3] [5]));
  SDFFQX1LVT \fifo_mem_reg[3][6] (.CK (clk), .D (\fifo_mem[3] [6]), .SI
       (din[6]), .SE (n_157), .Q (\fifo_mem[3] [6]));
  SDFFQX1LVT \fifo_mem_reg[3][8] (.CK (clk), .D (\fifo_mem[3] [8]), .SI
       (din[8]), .SE (n_157), .Q (\fifo_mem[3] [8]));
  SDFFQX1LVT \fifo_mem_reg[3][9] (.CK (clk), .D (\fifo_mem[3] [9]), .SI
       (din[9]), .SE (n_157), .Q (\fifo_mem[3] [9]));
  SDFFQX1LVT \fifo_mem_reg[3][10] (.CK (clk), .D (\fifo_mem[3] [10]),
       .SI (din[10]), .SE (n_157), .Q (\fifo_mem[3] [10]));
  SDFFQX1LVT \fifo_mem_reg[3][12] (.CK (clk), .D (\fifo_mem[3] [12]),
       .SI (din[12]), .SE (n_157), .Q (\fifo_mem[3] [12]));
  SDFFQX1LVT \fifo_mem_reg[3][13] (.CK (clk), .D (\fifo_mem[3] [13]),
       .SI (din[13]), .SE (n_157), .Q (\fifo_mem[3] [13]));
  SDFFQX1LVT \fifo_mem_reg[3][14] (.CK (clk), .D (\fifo_mem[3] [14]),
       .SI (din[14]), .SE (n_157), .Q (\fifo_mem[3] [14]));
  SDFFQX1LVT \fifo_mem_reg[4][11] (.CK (clk), .D (\fifo_mem[4] [11]),
       .SI (din[11]), .SE (n_114), .Q (\fifo_mem[4] [11]));
  SDFFQX1LVT \fifo_mem_reg[1][10] (.CK (clk), .D (din[10]), .SI
       (\fifo_mem[1] [10]), .SE (n_112), .Q (\fifo_mem[1] [10]));
  SDFFQX1LVT \fifo_mem_reg[1][11] (.CK (clk), .D (din[11]), .SI
       (\fifo_mem[1] [11]), .SE (n_112), .Q (\fifo_mem[1] [11]));
  SDFFQX1LVT \fifo_mem_reg[2][11] (.CK (clk), .D (din[11]), .SI
       (\fifo_mem[2] [11]), .SE (n_111), .Q (\fifo_mem[2] [11]));
  SDFFQX1LVT \fifo_mem_reg[1][15] (.CK (clk), .D (din[15]), .SI
       (\fifo_mem[1] [15]), .SE (n_112), .Q (\fifo_mem[1] [15]));
  SDFFQX1LVT \fifo_mem_reg[2][7] (.CK (clk), .D (din[7]), .SI
       (\fifo_mem[2] [7]), .SE (n_111), .Q (\fifo_mem[2] [7]));
  SDFFQX1LVT \fifo_mem_reg[2][3] (.CK (clk), .D (din[3]), .SI
       (\fifo_mem[2] [3]), .SE (n_111), .Q (\fifo_mem[2] [3]));
  SDFFQX1LVT \fifo_mem_reg[1][0] (.CK (clk), .D (din[0]), .SI
       (\fifo_mem[1] [0]), .SE (n_112), .Q (\fifo_mem[1] [0]));
  SDFFQX1LVT \fifo_mem_reg[1][1] (.CK (clk), .D (din[1]), .SI
       (\fifo_mem[1] [1]), .SE (n_112), .Q (\fifo_mem[1] [1]));
  SDFFQX1LVT \fifo_mem_reg[1][2] (.CK (clk), .D (din[2]), .SI
       (\fifo_mem[1] [2]), .SE (n_112), .Q (\fifo_mem[1] [2]));
  SDFFQX1LVT \fifo_mem_reg[1][3] (.CK (clk), .D (din[3]), .SI
       (\fifo_mem[1] [3]), .SE (n_112), .Q (\fifo_mem[1] [3]));
  SDFFQX1LVT \fifo_mem_reg[1][4] (.CK (clk), .D (din[4]), .SI
       (\fifo_mem[1] [4]), .SE (n_112), .Q (\fifo_mem[1] [4]));
  SDFFQX1LVT \fifo_mem_reg[1][5] (.CK (clk), .D (din[5]), .SI
       (\fifo_mem[1] [5]), .SE (n_112), .Q (\fifo_mem[1] [5]));
  SDFFQX1LVT \fifo_mem_reg[1][6] (.CK (clk), .D (din[6]), .SI
       (\fifo_mem[1] [6]), .SE (n_112), .Q (\fifo_mem[1] [6]));
  SDFFQX1LVT \fifo_mem_reg[1][8] (.CK (clk), .D (din[8]), .SI
       (\fifo_mem[1] [8]), .SE (n_112), .Q (\fifo_mem[1] [8]));
  SDFFQX1LVT \fifo_mem_reg[1][9] (.CK (clk), .D (din[9]), .SI
       (\fifo_mem[1] [9]), .SE (n_112), .Q (\fifo_mem[1] [9]));
  SDFFQX1LVT \fifo_mem_reg[2][15] (.CK (clk), .D (din[15]), .SI
       (\fifo_mem[2] [15]), .SE (n_111), .Q (\fifo_mem[2] [15]));
  SDFFQX1LVT \fifo_mem_reg[1][7] (.CK (clk), .D (din[7]), .SI
       (\fifo_mem[1] [7]), .SE (n_112), .Q (\fifo_mem[1] [7]));
  SDFFQX1LVT \fifo_mem_reg[1][13] (.CK (clk), .D (din[13]), .SI
       (\fifo_mem[1] [13]), .SE (n_112), .Q (\fifo_mem[1] [13]));
  SDFFQX1LVT \fifo_mem_reg[1][14] (.CK (clk), .D (din[14]), .SI
       (\fifo_mem[1] [14]), .SE (n_112), .Q (\fifo_mem[1] [14]));
  SDFFQX1LVT \fifo_mem_reg[2][0] (.CK (clk), .D (din[0]), .SI
       (\fifo_mem[2] [0]), .SE (n_111), .Q (\fifo_mem[2] [0]));
  SDFFQX1LVT \fifo_mem_reg[2][1] (.CK (clk), .D (din[1]), .SI
       (\fifo_mem[2] [1]), .SE (n_111), .Q (\fifo_mem[2] [1]));
  SDFFQX1LVT \fifo_mem_reg[2][2] (.CK (clk), .D (din[2]), .SI
       (\fifo_mem[2] [2]), .SE (n_111), .Q (\fifo_mem[2] [2]));
  SDFFQX1LVT \fifo_mem_reg[2][4] (.CK (clk), .D (din[4]), .SI
       (\fifo_mem[2] [4]), .SE (n_111), .Q (\fifo_mem[2] [4]));
  SDFFQX1LVT \fifo_mem_reg[2][5] (.CK (clk), .D (din[5]), .SI
       (\fifo_mem[2] [5]), .SE (n_111), .Q (\fifo_mem[2] [5]));
  SDFFQX1LVT \fifo_mem_reg[2][6] (.CK (clk), .D (din[6]), .SI
       (\fifo_mem[2] [6]), .SE (n_111), .Q (\fifo_mem[2] [6]));
  SDFFQX1LVT \fifo_mem_reg[2][8] (.CK (clk), .D (din[8]), .SI
       (\fifo_mem[2] [8]), .SE (n_111), .Q (\fifo_mem[2] [8]));
  SDFFQX1LVT \fifo_mem_reg[2][9] (.CK (clk), .D (din[9]), .SI
       (\fifo_mem[2] [9]), .SE (n_111), .Q (\fifo_mem[2] [9]));
  SDFFQX1LVT \fifo_mem_reg[2][10] (.CK (clk), .D (din[10]), .SI
       (\fifo_mem[2] [10]), .SE (n_111), .Q (\fifo_mem[2] [10]));
  SDFFQX1LVT \fifo_mem_reg[2][12] (.CK (clk), .D (din[12]), .SI
       (\fifo_mem[2] [12]), .SE (n_111), .Q (\fifo_mem[2] [12]));
  SDFFQX1LVT \fifo_mem_reg[2][13] (.CK (clk), .D (din[13]), .SI
       (\fifo_mem[2] [13]), .SE (n_111), .Q (\fifo_mem[2] [13]));
  SDFFQX1LVT \fifo_mem_reg[2][14] (.CK (clk), .D (din[14]), .SI
       (\fifo_mem[2] [14]), .SE (n_111), .Q (\fifo_mem[2] [14]));
  SDFFQX1LVT \fifo_mem_reg[1][12] (.CK (clk), .D (din[12]), .SI
       (\fifo_mem[1] [12]), .SE (n_112), .Q (\fifo_mem[1] [12]));
  NAND2X1LVT g5242__8428(.A (n_57), .B (n_83), .Y (n_110));
  NAND2X1LVT g5227__5526(.A (n_59), .B (n_76), .Y (n_109));
  NAND2X1LVT g5228__6783(.A (n_56), .B (n_84), .Y (n_108));
  NAND2X1LVT g5229__3680(.A (n_55), .B (n_85), .Y (n_107));
  NAND2X1LVT g5230__1617(.A (n_62), .B (n_79), .Y (n_106));
  NAND2X1LVT g5231__2802(.A (n_60), .B (n_90), .Y (n_105));
  NAND2X1LVT g5232__1705(.A (n_69), .B (n_74), .Y (n_104));
  NAND2X1LVT g5233__5122(.A (n_54), .B (n_71), .Y (n_103));
  NAND2X1LVT g5234__8246(.A (n_68), .B (n_77), .Y (n_102));
  NAND2X1LVT g5235__7098(.A (n_64), .B (n_91), .Y (n_101));
  NAND2X1LVT g5236__6131(.A (n_65), .B (n_78), .Y (n_100));
  NAND2X1LVT g5237__1881(.A (n_63), .B (n_73), .Y (n_99));
  NAND2X1LVT g5238__5115(.A (n_70), .B (n_72), .Y (n_98));
  NAND2X1LVT g5239__7482(.A (n_67), .B (n_75), .Y (n_97));
  NAND2X1LVT g5240__4733(.A (n_66), .B (n_88), .Y (n_96));
  NAND2X1LVT g5241__6161(.A (n_61), .B (n_80), .Y (n_95));
  SDFFQX1LVT \fifo_mem_reg[7][3] (.CK (clk), .D (\fifo_mem[7] [3]), .SI
       (din[3]), .SE (n_94), .Q (\fifo_mem[7] [3]));
  SDFFQX1LVT \fifo_mem_reg[5][15] (.CK (clk), .D (\fifo_mem[5] [15]),
       .SI (din[15]), .SE (n_158), .Q (\fifo_mem[5] [15]));
  SDFFQX1LVT \fifo_mem_reg[6][15] (.CK (clk), .D (\fifo_mem[6] [15]),
       .SI (din[15]), .SE (n_159), .Q (\fifo_mem[6] [15]));
  SDFFQX1LVT \fifo_mem_reg[7][15] (.CK (clk), .D (\fifo_mem[7] [15]),
       .SI (din[15]), .SE (n_94), .Q (\fifo_mem[7] [15]));
  SDFFQX1LVT \fifo_mem_reg[7][11] (.CK (clk), .D (\fifo_mem[7] [11]),
       .SI (din[11]), .SE (n_94), .Q (\fifo_mem[7] [11]));
  SDFFQX1LVT \fifo_mem_reg[6][11] (.CK (clk), .D (\fifo_mem[6] [11]),
       .SI (din[11]), .SE (n_159), .Q (\fifo_mem[6] [11]));
  SDFFQX1LVT \fifo_mem_reg[7][7] (.CK (clk), .D (\fifo_mem[7] [7]), .SI
       (din[7]), .SE (n_94), .Q (\fifo_mem[7] [7]));
  SDFFQX1LVT \fifo_mem_reg[7][14] (.CK (clk), .D (\fifo_mem[7] [14]),
       .SI (din[14]), .SE (n_94), .Q (\fifo_mem[7] [14]));
  SDFFQX1LVT \fifo_mem_reg[5][0] (.CK (clk), .D (\fifo_mem[5] [0]), .SI
       (din[0]), .SE (n_158), .Q (\fifo_mem[5] [0]));
  SDFFQX1LVT \fifo_mem_reg[5][1] (.CK (clk), .D (\fifo_mem[5] [1]), .SI
       (din[1]), .SE (n_158), .Q (\fifo_mem[5] [1]));
  SDFFQX1LVT \fifo_mem_reg[5][2] (.CK (clk), .D (\fifo_mem[5] [2]), .SI
       (din[2]), .SE (n_158), .Q (\fifo_mem[5] [2]));
  SDFFQX1LVT \fifo_mem_reg[5][3] (.CK (clk), .D (\fifo_mem[5] [3]), .SI
       (din[3]), .SE (n_158), .Q (\fifo_mem[5] [3]));
  SDFFQX1LVT \fifo_mem_reg[5][4] (.CK (clk), .D (\fifo_mem[5] [4]), .SI
       (din[4]), .SE (n_158), .Q (\fifo_mem[5] [4]));
  SDFFQX1LVT \fifo_mem_reg[5][5] (.CK (clk), .D (\fifo_mem[5] [5]), .SI
       (din[5]), .SE (n_158), .Q (\fifo_mem[5] [5]));
  SDFFQX1LVT \fifo_mem_reg[5][6] (.CK (clk), .D (\fifo_mem[5] [6]), .SI
       (din[6]), .SE (n_158), .Q (\fifo_mem[5] [6]));
  SDFFQX1LVT \fifo_mem_reg[5][11] (.CK (clk), .D (\fifo_mem[5] [11]),
       .SI (din[11]), .SE (n_158), .Q (\fifo_mem[5] [11]));
  SDFFQX1LVT \fifo_mem_reg[6][12] (.CK (clk), .D (\fifo_mem[6] [12]),
       .SI (din[12]), .SE (n_159), .Q (\fifo_mem[6] [12]));
  SDFFQX1LVT \fifo_mem_reg[5][9] (.CK (clk), .D (\fifo_mem[5] [9]), .SI
       (din[9]), .SE (n_158), .Q (\fifo_mem[5] [9]));
  SDFFQX1LVT \fifo_mem_reg[5][10] (.CK (clk), .D (\fifo_mem[5] [10]),
       .SI (din[10]), .SE (n_158), .Q (\fifo_mem[5] [10]));
  SDFFQX1LVT \fifo_mem_reg[5][12] (.CK (clk), .D (\fifo_mem[5] [12]),
       .SI (din[12]), .SE (n_158), .Q (\fifo_mem[5] [12]));
  SDFFQX1LVT \fifo_mem_reg[5][13] (.CK (clk), .D (\fifo_mem[5] [13]),
       .SI (din[13]), .SE (n_158), .Q (\fifo_mem[5] [13]));
  SDFFQX1LVT \fifo_mem_reg[5][14] (.CK (clk), .D (\fifo_mem[5] [14]),
       .SI (din[14]), .SE (n_158), .Q (\fifo_mem[5] [14]));
  SDFFQX1LVT \fifo_mem_reg[6][0] (.CK (clk), .D (\fifo_mem[6] [0]), .SI
       (din[0]), .SE (n_159), .Q (\fifo_mem[6] [0]));
  SDFFQX1LVT \fifo_mem_reg[6][1] (.CK (clk), .D (\fifo_mem[6] [1]), .SI
       (din[1]), .SE (n_159), .Q (\fifo_mem[6] [1]));
  SDFFQX1LVT \fifo_mem_reg[6][2] (.CK (clk), .D (\fifo_mem[6] [2]), .SI
       (din[2]), .SE (n_159), .Q (\fifo_mem[6] [2]));
  SDFFQX1LVT \fifo_mem_reg[6][3] (.CK (clk), .D (\fifo_mem[6] [3]), .SI
       (din[3]), .SE (n_159), .Q (\fifo_mem[6] [3]));
  SDFFQX1LVT \fifo_mem_reg[6][4] (.CK (clk), .D (\fifo_mem[6] [4]), .SI
       (din[4]), .SE (n_159), .Q (\fifo_mem[6] [4]));
  SDFFQX1LVT \fifo_mem_reg[6][5] (.CK (clk), .D (\fifo_mem[6] [5]), .SI
       (din[5]), .SE (n_159), .Q (\fifo_mem[6] [5]));
  SDFFQX1LVT \fifo_mem_reg[6][6] (.CK (clk), .D (\fifo_mem[6] [6]), .SI
       (din[6]), .SE (n_159), .Q (\fifo_mem[6] [6]));
  SDFFQX1LVT \fifo_mem_reg[6][8] (.CK (clk), .D (\fifo_mem[6] [8]), .SI
       (din[8]), .SE (n_159), .Q (\fifo_mem[6] [8]));
  SDFFQX1LVT \fifo_mem_reg[6][9] (.CK (clk), .D (\fifo_mem[6] [9]), .SI
       (din[9]), .SE (n_159), .Q (\fifo_mem[6] [9]));
  SDFFQX1LVT \fifo_mem_reg[6][10] (.CK (clk), .D (\fifo_mem[6] [10]),
       .SI (din[10]), .SE (n_159), .Q (\fifo_mem[6] [10]));
  SDFFQX1LVT \fifo_mem_reg[5][8] (.CK (clk), .D (\fifo_mem[5] [8]), .SI
       (din[8]), .SE (n_158), .Q (\fifo_mem[5] [8]));
  SDFFQX1LVT \fifo_mem_reg[6][13] (.CK (clk), .D (\fifo_mem[6] [13]),
       .SI (din[13]), .SE (n_159), .Q (\fifo_mem[6] [13]));
  SDFFQX1LVT \fifo_mem_reg[6][14] (.CK (clk), .D (\fifo_mem[6] [14]),
       .SI (din[14]), .SE (n_159), .Q (\fifo_mem[6] [14]));
  SDFFQX1LVT \fifo_mem_reg[7][0] (.CK (clk), .D (\fifo_mem[7] [0]), .SI
       (din[0]), .SE (n_94), .Q (\fifo_mem[7] [0]));
  SDFFQX1LVT \fifo_mem_reg[7][1] (.CK (clk), .D (\fifo_mem[7] [1]), .SI
       (din[1]), .SE (n_94), .Q (\fifo_mem[7] [1]));
  SDFFQX1LVT \fifo_mem_reg[7][2] (.CK (clk), .D (\fifo_mem[7] [2]), .SI
       (din[2]), .SE (n_94), .Q (\fifo_mem[7] [2]));
  SDFFQX1LVT \fifo_mem_reg[7][4] (.CK (clk), .D (\fifo_mem[7] [4]), .SI
       (din[4]), .SE (n_94), .Q (\fifo_mem[7] [4]));
  SDFFQX1LVT \fifo_mem_reg[7][5] (.CK (clk), .D (\fifo_mem[7] [5]), .SI
       (din[5]), .SE (n_94), .Q (\fifo_mem[7] [5]));
  SDFFQX1LVT \fifo_mem_reg[7][6] (.CK (clk), .D (\fifo_mem[7] [6]), .SI
       (din[6]), .SE (n_94), .Q (\fifo_mem[7] [6]));
  SDFFQX1LVT \fifo_mem_reg[7][8] (.CK (clk), .D (\fifo_mem[7] [8]), .SI
       (din[8]), .SE (n_94), .Q (\fifo_mem[7] [8]));
  SDFFQX1LVT \fifo_mem_reg[7][9] (.CK (clk), .D (\fifo_mem[7] [9]), .SI
       (din[9]), .SE (n_94), .Q (\fifo_mem[7] [9]));
  SDFFQX1LVT \fifo_mem_reg[7][10] (.CK (clk), .D (\fifo_mem[7] [10]),
       .SI (din[10]), .SE (n_94), .Q (\fifo_mem[7] [10]));
  SDFFQX1LVT \fifo_mem_reg[7][12] (.CK (clk), .D (\fifo_mem[7] [12]),
       .SI (din[12]), .SE (n_94), .Q (\fifo_mem[7] [12]));
  SDFFQX1LVT \fifo_mem_reg[7][13] (.CK (clk), .D (\fifo_mem[7] [13]),
       .SI (din[13]), .SE (n_94), .Q (\fifo_mem[7] [13]));
  SDFFQX1LVT \fifo_mem_reg[5][7] (.CK (clk), .D (\fifo_mem[5] [7]), .SI
       (din[7]), .SE (n_158), .Q (\fifo_mem[5] [7]));
  SDFFQX1LVT \fifo_mem_reg[6][7] (.CK (clk), .D (\fifo_mem[6] [7]), .SI
       (din[7]), .SE (n_159), .Q (\fifo_mem[6] [7]));
  NOR2X1LVT g5251__9315(.A (wptr[0]), .B (n_58), .Y (n_121));
  AOI222X1LVT g5254__9945(.A0 (\fifo_mem[6] [14]), .A1 (n_89), .B0
       (\fifo_mem[7] [14]), .B1 (n_87), .C0 (\fifo_mem[4] [14]), .C1
       (n_86), .Y (n_91));
  AOI222X1LVT g5243__2883(.A0 (\fifo_mem[5] [7]), .A1 (n_82), .B0
       (\fifo_mem[6] [7]), .B1 (n_89), .C0 (\fifo_mem[3] [7]), .C1
       (n_81), .Y (n_90));
  AOI222X1LVT g5244__2346(.A0 (\fifo_mem[6] [1]), .A1 (n_89), .B0
       (\fifo_mem[7] [1]), .B1 (n_87), .C0 (\fifo_mem[4] [1]), .C1
       (n_86), .Y (n_88));
  AOI222X1LVT g5245__1666(.A0 (\fifo_mem[6] [8]), .A1 (n_89), .B0
       (\fifo_mem[7] [8]), .B1 (n_87), .C0 (\fifo_mem[4] [8]), .C1
       (n_86), .Y (n_85));
  AOI222X1LVT g5246__7410(.A0 (\fifo_mem[6] [2]), .A1 (n_89), .B0
       (\fifo_mem[7] [2]), .B1 (n_87), .C0 (\fifo_mem[4] [2]), .C1
       (n_86), .Y (n_84));
  AOI222X1LVT g5247__6417(.A0 (\fifo_mem[5] [6]), .A1 (n_82), .B0
       (\fifo_mem[6] [6]), .B1 (n_89), .C0 (\fifo_mem[3] [6]), .C1
       (n_81), .Y (n_83));
  AOI222X1LVT g5263__5477(.A0 (\fifo_mem[6] [15]), .A1 (n_89), .B0
       (\fifo_mem[7] [15]), .B1 (n_87), .C0 (\fifo_mem[4] [15]), .C1
       (n_86), .Y (n_80));
  AOI222X1LVT g5253__2398(.A0 (\fifo_mem[6] [0]), .A1 (n_89), .B0
       (\fifo_mem[7] [0]), .B1 (n_87), .C0 (\fifo_mem[4] [0]), .C1
       (n_86), .Y (n_79));
  NOR2BX1LVT g5252__5107(.AN (n_37), .B (wptr[0]), .Y (n_114));
  AOI222X1LVT g5260__6260(.A0 (\fifo_mem[6] [12]), .A1 (n_89), .B0
       (\fifo_mem[7] [12]), .B1 (n_87), .C0 (\fifo_mem[4] [12]), .C1
       (n_86), .Y (n_78));
  AOI222X1LVT g5257__4319(.A0 (\fifo_mem[6] [11]), .A1 (n_89), .B0
       (\fifo_mem[7] [11]), .B1 (n_87), .C0 (\fifo_mem[4] [11]), .C1
       (n_86), .Y (n_77));
  AOI222X1LVT g5258__8428(.A0 (\fifo_mem[5] [9]), .A1 (n_82), .B0
       (\fifo_mem[6] [9]), .B1 (n_89), .C0 (\fifo_mem[3] [9]), .C1
       (n_81), .Y (n_76));
  AOI222X1LVT g5259__5526(.A0 (\fifo_mem[5] [4]), .A1 (n_82), .B0
       (\fifo_mem[6] [4]), .B1 (n_89), .C0 (\fifo_mem[3] [4]), .C1
       (n_81), .Y (n_75));
  AOI222X1LVT g5256__6783(.A0 (\fifo_mem[6] [3]), .A1 (n_89), .B0
       (\fifo_mem[7] [3]), .B1 (n_87), .C0 (\fifo_mem[4] [3]), .C1
       (n_86), .Y (n_74));
  AOI222X1LVT g5261__3680(.A0 (\fifo_mem[6] [13]), .A1 (n_89), .B0
       (\fifo_mem[7] [13]), .B1 (n_87), .C0 (\fifo_mem[4] [13]), .C1
       (n_86), .Y (n_73));
  AOI222X1LVT g5262__1617(.A0 (\fifo_mem[5] [5]), .A1 (n_82), .B0
       (\fifo_mem[6] [5]), .B1 (n_89), .C0 (\fifo_mem[3] [5]), .C1
       (n_81), .Y (n_72));
  AOI222X1LVT g5255__2802(.A0 (\fifo_mem[6] [10]), .A1 (n_89), .B0
       (\fifo_mem[7] [10]), .B1 (n_87), .C0 (\fifo_mem[4] [10]), .C1
       (n_86), .Y (n_71));
  AOI22X1LVT g5299__5122(.A0 (\fifo_mem[4] [5]), .A1 (n_86), .B0
       (\fifo_mem[7] [5]), .B1 (n_87), .Y (n_70));
  AOI22X1LVT g5289__8246(.A0 (\fifo_mem[5] [3]), .A1 (n_82), .B0
       (\fifo_mem[3] [3]), .B1 (n_81), .Y (n_69));
  AOI22X1LVT g5291__7098(.A0 (\fifo_mem[5] [11]), .A1 (n_82), .B0
       (\fifo_mem[3] [11]), .B1 (n_81), .Y (n_68));
  AOI22X1LVT g5294__6131(.A0 (\fifo_mem[4] [4]), .A1 (n_86), .B0
       (\fifo_mem[7] [4]), .B1 (n_87), .Y (n_67));
  AOI22X1LVT g5295__1881(.A0 (\fifo_mem[5] [1]), .A1 (n_82), .B0
       (\fifo_mem[3] [1]), .B1 (n_81), .Y (n_66));
  AOI22X1LVT g5296__5115(.A0 (\fifo_mem[5] [12]), .A1 (n_82), .B0
       (\fifo_mem[3] [12]), .B1 (n_81), .Y (n_65));
  AOI22X1LVT g5297__7482(.A0 (\fifo_mem[5] [14]), .A1 (n_82), .B0
       (\fifo_mem[3] [14]), .B1 (n_81), .Y (n_64));
  AOI22X1LVT g5298__4733(.A0 (\fifo_mem[5] [13]), .A1 (n_82), .B0
       (\fifo_mem[3] [13]), .B1 (n_81), .Y (n_63));
  AOI22X1LVT g5288__6161(.A0 (\fifo_mem[5] [0]), .A1 (n_82), .B0
       (\fifo_mem[3] [0]), .B1 (n_81), .Y (n_62));
  AOI22X1LVT g5302__9315(.A0 (\fifo_mem[5] [15]), .A1 (n_82), .B0
       (\fifo_mem[3] [15]), .B1 (n_81), .Y (n_61));
  AOI22X1LVT g5269__9945(.A0 (\fifo_mem[4] [7]), .A1 (n_86), .B0
       (\fifo_mem[7] [7]), .B1 (n_87), .Y (n_60));
  AOI22X1LVT g5264__2883(.A0 (\fifo_mem[4] [9]), .A1 (n_86), .B0
       (\fifo_mem[7] [9]), .B1 (n_87), .Y (n_59));
  NAND2X1LVT g5265__2346(.A (n_11), .B (n_160), .Y (n_58));
  AOI22X1LVT g5270__1666(.A0 (\fifo_mem[4] [6]), .A1 (n_86), .B0
       (\fifo_mem[7] [6]), .B1 (n_87), .Y (n_57));
  AOI22X1LVT g5272__7410(.A0 (\fifo_mem[5] [2]), .A1 (n_82), .B0
       (\fifo_mem[3] [2]), .B1 (n_81), .Y (n_56));
  AOI22X1LVT g5274__6417(.A0 (\fifo_mem[5] [8]), .A1 (n_82), .B0
       (\fifo_mem[3] [8]), .B1 (n_81), .Y (n_55));
  AOI22X1LVT g5287__5477(.A0 (\fifo_mem[5] [10]), .A1 (n_82), .B0
       (\fifo_mem[3] [10]), .B1 (n_81), .Y (n_54));
  NAND2X1LVT g5283__2398(.A (n_7), .B (n_160), .Y (n_111));
  NAND2X1LVT g5282__5107(.A (n_8), .B (n_160), .Y (n_112));
  AOI22X1LVT g5266__6260(.A0 (\fifo_mem[2] [7]), .A1 (n_131), .B0
       (dout[7]), .B1 (n_133), .Y (n_52));
  AOI22X1LVT g5292__4319(.A0 (\fifo_mem[0] [13]), .A1 (n_127), .B0
       (\fifo_mem[1] [13]), .B1 (n_123), .Y (n_51));
  AOI22X1LVT g5293__8428(.A0 (\fifo_mem[2] [12]), .A1 (n_131), .B0
       (dout[12]), .B1 (n_133), .Y (n_50));
  AOI22XLLVT g5300__5526(.A0 (\fifo_mem[1] [1]), .A1 (n_123), .B0
       (dout[1]), .B1 (n_133), .Y (n_49));
  AOI22XLLVT g5301__6783(.A0 (\fifo_mem[1] [14]), .A1 (n_123), .B0
       (dout[14]), .B1 (n_133), .Y (n_48));
  AOI22X1LVT g5303__3680(.A0 (\fifo_mem[0] [5]), .A1 (n_127), .B0
       (\fifo_mem[1] [5]), .B1 (n_123), .Y (n_47));
  AOI22X1LVT g5290__1617(.A0 (\fifo_mem[0] [4]), .A1 (n_127), .B0
       (\fifo_mem[1] [4]), .B1 (n_123), .Y (n_46));
  AOI22X1LVT g5267__2802(.A0 (\fifo_mem[2] [0]), .A1 (n_131), .B0
       (dout[0]), .B1 (n_133), .Y (n_44));
  AOI22X1LVT g5271__1705(.A0 (\fifo_mem[0] [8]), .A1 (n_127), .B0
       (\fifo_mem[1] [8]), .B1 (n_123), .Y (n_43));
  AOI22X1LVT g5268__5122(.A0 (\fifo_mem[0] [2]), .A1 (n_127), .B0
       (\fifo_mem[1] [2]), .B1 (n_123), .Y (n_42));
  SDFFRHQX1LVT \wptr_reg[1] (.RN (rstn), .CK (clk), .D (n_19), .SI
       (wptr[1]), .SE (n_34), .Q (wptr[1]));
  AOI22X1LVT g5286__8246(.A0 (\fifo_mem[2] [10]), .A1 (n_131), .B0
       (dout[10]), .B1 (n_133), .Y (n_41));
  AOI22XLLVT g5273__7098(.A0 (\fifo_mem[1] [6]), .A1 (n_123), .B0
       (dout[6]), .B1 (n_133), .Y (n_40));
  AOI22X1LVT g5275__6131(.A0 (\fifo_mem[2] [9]), .A1 (n_131), .B0
       (dout[9]), .B1 (n_133), .Y (n_39));
  AOI22X1LVT g5276__1881(.A0 (\fifo_mem[0] [3]), .A1 (n_127), .B0
       (\fifo_mem[2] [3]), .B1 (n_131), .Y (n_38));
  NOR2XLLVT g5277__5115(.A (wptr[1]), .B (n_32), .Y (n_37));
  AOI22X1LVT g5285__7482(.A0 (\fifo_mem[2] [11]), .A1 (n_131), .B0
       (dout[11]), .B1 (n_133), .Y (n_36));
  AOI22XLLVT g5284__4733(.A0 (\fifo_mem[1] [15]), .A1 (n_123), .B0
       (dout[15]), .B1 (n_133), .Y (n_35));
  SDFFRHQX1LVT \wptr_reg[2] (.RN (rstn), .CK (clk), .D (n_17), .SI
       (wptr[2]), .SE (n_34), .Q (wptr[2]));
  SDFFRHQX1LVT \wptr_reg[0] (.RN (rstn), .CK (clk), .D (n_5), .SI
       (wptr[0]), .SE (n_34), .Q (wptr[0]));
  NOR2X1LVT g5278__6161(.A (n_33), .B (n_32), .Y (n_94));
  NAND3BXLLVT g5304__2346(.AN (n_34), .B (wptr[2]), .C (rstn), .Y
       (n_32));
  AND2X1LVT g5311__1666(.A (n_31), .B (rptr[0]), .Y (n_82));
  NOR2BX1LVT g5314__7410(.AN (n_31), .B (rptr[0]), .Y (n_86));
  NOR2X1LVT g5316__6417(.A (rptr[0]), .B (n_26), .Y (n_89));
  NOR2X1LVT g5312__5477(.A (n_4), .B (n_30), .Y (n_123));
  NOR2X1LVT g5313__2398(.A (rptr[0]), .B (n_30), .Y (n_127));
  OAI21XLLVT g5321__5107(.A0 (n_25), .A1 (n_27), .B0 (n_21), .Y (n_29));
  NOR2X1LVT g5315__6260(.A (rptr[0]), .B (n_23), .Y (n_131));
  NAND2BX1LVT g5307__4319(.AN (full), .B (wr_en), .Y (n_34));
  SDFFRHQX1LVT \rptr_reg[0] (.RN (rstn), .CK (clk), .D (n_27), .SI
       (n_133), .SE (rptr[0]), .Q (rptr[0]));
  OR2XLLVT g5322__8428(.A (n_25), .B (n_24), .Y (n_26));
  NOR2X1LVT g5318__5526(.A (rptr[1]), .B (n_24), .Y (n_31));
  NOR2X1LVT g5320__6783(.A (n_20), .B (n_24), .Y (n_87));
  NAND2X1LVT g5317__3680(.A (rptr[1]), .B (n_22), .Y (n_23));
  NAND2X1LVT g5319__1617(.A (n_25), .B (n_22), .Y (n_30));
  OAI211X1LVT g5328__2802(.A0 (rptr[0]), .A1 (rptr[1]), .B0 (n_20), .C0
       (n_27), .Y (n_21));
  SDFFRHQX1LVT \rptr_reg[2] (.RN (rstn), .CK (clk), .D (n_9), .SI
       (rptr[2]), .SE (n_133), .Q (rptr[2]));
  NOR2BX1LVT g5324__1705(.AN (n_22), .B (n_20), .Y (n_81));
  AOI221X1LVT g5323__5122(.A0 (n_25), .A1 (n_19), .B0 (rptr[1]), .B1
       (n_10), .C0 (n_18), .Y (full));
  NAND2X1LVT g5326__8246(.A (rptr[2]), .B (n_27), .Y (n_24));
  NOR2X1LVT g5325__7098(.A (rptr[2]), .B (n_133), .Y (n_22));
  INVX1LVT g5329(.A (n_133), .Y (n_27));
  OAI211X1LVT g5327__6131(.A0 (n_13), .A1 (n_17), .B0 (n_15), .C0
       (n_14), .Y (n_18));
  NAND2BX1LVT g5330__1881(.AN (empty), .B (rd_en), .Y (n_133));
  NOR2XLLVT g5333__5115(.A (n_15), .B (n_12), .Y (empty));
  NAND2XLLVT g5332__7482(.A (n_13), .B (n_17), .Y (n_14));
  OAI221X1LVT g5334__4733(.A0 (wptr[1]), .A1 (n_25), .B0 (rptr[1]), .B1
       (n_11), .C0 (n_156), .Y (n_12));
  INVX1LVT g5336(.A (n_10), .Y (n_19));
  MXI2XLLVT g5331__6161(.A (rptr[2]), .B (n_13), .S0 (n_20), .Y (n_9));
  NOR2X1LVT g5337__9315(.A (n_8), .B (n_7), .Y (n_10));
  XNOR2X1LVT g5335__9945(.A (wptr[2]), .B (n_33), .Y (n_17));
  AOI22X1LVT g5339__2346(.A0 (n_5), .A1 (n_4), .B0 (wptr[0]), .B1
       (rptr[0]), .Y (n_15));
  NOR2X1LVT g5344__1666(.A (wptr[1]), .B (n_5), .Y (n_8));
  NOR2X1LVT g5345__7410(.A (wptr[0]), .B (n_11), .Y (n_7));
  NAND2X1LVT g5340__6417(.A (wptr[0]), .B (wptr[1]), .Y (n_33));
  NAND2X1LVT g5341__5477(.A (rptr[0]), .B (rptr[1]), .Y (n_20));
  INVX1LVT g5350(.A (wptr[1]), .Y (n_11));
  INVX1LVT g5348(.A (wptr[0]), .Y (n_5));
  INVX1LVT g5351(.A (rptr[0]), .Y (n_4));
  INVX1LVT g5347(.A (rptr[2]), .Y (n_13));
  MXI2XLLVT g2(.A (rptr[2]), .B (n_13), .S0 (wptr[2]), .Y (n_156));
  DFFRX1LVT \rptr_reg[1] (.RN (rstn), .CK (clk), .D (n_29), .Q
       (rptr[1]), .QN (n_25));
  NOR2BX1LVT g5505(.AN (n_160), .B (n_33), .Y (n_157));
  NOR2BX1LVT g5506(.AN (n_8), .B (n_32), .Y (n_158));
  NOR2BX1LVT g5507(.AN (n_7), .B (n_32), .Y (n_159));
  NOR3BX1LVT g5508(.AN (rstn), .B (wptr[2]), .C (n_34), .Y (n_160));
endmodule

