
// Generated by Cadence Genus(TM) Synthesis Solution 23.16-s067_1
// Generated on: Mar 17 2026 08:34:04 IST (Mar 17 2026 03:04:04 UTC)

// Verification Directory fv/sync_fifo 

module sync_fifo(clk, rstn, wr_en, rd_en, din, dout, empty, full);
  input clk, rstn, wr_en, rd_en;
  input [15:0] din;
  output [15:0] dout;
  output empty, full;
  wire clk, rstn, wr_en, rd_en;
  wire [15:0] din;
  wire [15:0] dout;
  wire empty, full;
  wire [15:0] \fifo_mem[0] ;
  wire [15:0] \fifo_mem[4] ;
  wire [15:0] \fifo_mem[2] ;
  wire [15:0] \fifo_mem[1] ;
  wire [15:0] \fifo_mem[6] ;
  wire [15:0] \fifo_mem[7] ;
  wire [15:0] \fifo_mem[5] ;
  wire [15:0] \fifo_mem[3] ;
  wire [2:0] wptr;
  wire [2:0] rptr;
  wire n_1, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_214, n_215, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, n_223, n_224, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_231, n_232, n_233;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_290, n_291, n_292, n_293;
  DFFRHQX1LVT \dout_reg[0] (.RN (rstn), .CK (clk), .D (n_278), .Q
       (dout[0]));
  DFFRHQX1LVT \dout_reg[1] (.RN (rstn), .CK (clk), .D (n_273), .Q
       (dout[1]));
  DFFRHQX1LVT \dout_reg[6] (.RN (rstn), .CK (clk), .D (n_274), .Q
       (dout[6]));
  DFFRHQX1LVT \dout_reg[7] (.RN (rstn), .CK (clk), .D (n_283), .Q
       (dout[7]));
  DFFRHQX1LVT \dout_reg[8] (.RN (rstn), .CK (clk), .D (n_279), .Q
       (dout[8]));
  DFFRHQX1LVT \dout_reg[2] (.RN (rstn), .CK (clk), .D (n_272), .Q
       (dout[2]));
  DFFRHQX1LVT \dout_reg[9] (.RN (rstn), .CK (clk), .D (n_275), .Q
       (dout[9]));
  DFFRHQX1LVT \dout_reg[3] (.RN (rstn), .CK (clk), .D (n_276), .Q
       (dout[3]));
  DFFRHQX1LVT \dout_reg[10] (.RN (rstn), .CK (clk), .D (n_271), .Q
       (dout[10]));
  DFFRHQX1LVT \dout_reg[4] (.RN (rstn), .CK (clk), .D (n_270), .Q
       (dout[4]));
  DFFRHQX1LVT \dout_reg[11] (.RN (rstn), .CK (clk), .D (n_284), .Q
       (dout[11]));
  DFFRHQX1LVT \dout_reg[12] (.RN (rstn), .CK (clk), .D (n_282), .Q
       (dout[12]));
  DFFRHQX1LVT \dout_reg[5] (.RN (rstn), .CK (clk), .D (n_281), .Q
       (dout[5]));
  DFFRHQX1LVT \dout_reg[13] (.RN (rstn), .CK (clk), .D (n_280), .Q
       (dout[13]));
  DFFRHQX1LVT \dout_reg[14] (.RN (rstn), .CK (clk), .D (n_285), .Q
       (dout[14]));
  DFFRHQX1LVT \dout_reg[15] (.RN (rstn), .CK (clk), .D (n_277), .Q
       (dout[15]));
  NAND2X1LVT g5075__2398(.A (n_41), .B (n_239), .Y (n_285));
  DFFQXLLVT \fifo_mem_reg[0][1] (.CK (clk), .D (n_261), .Q
       (\fifo_mem[0] [1]));
  DFFQXLLVT \fifo_mem_reg[0][2] (.CK (clk), .D (n_258), .Q
       (\fifo_mem[0] [2]));
  DFFQXLLVT \fifo_mem_reg[0][3] (.CK (clk), .D (n_240), .Q
       (\fifo_mem[0] [3]));
  DFFQXLLVT \fifo_mem_reg[0][4] (.CK (clk), .D (n_242), .Q
       (\fifo_mem[0] [4]));
  DFFQXLLVT \fifo_mem_reg[0][5] (.CK (clk), .D (n_263), .Q
       (\fifo_mem[0] [5]));
  DFFQXLLVT \fifo_mem_reg[0][6] (.CK (clk), .D (n_248), .Q
       (\fifo_mem[0] [6]));
  DFFQXLLVT \fifo_mem_reg[0][7] (.CK (clk), .D (n_249), .Q
       (\fifo_mem[0] [7]));
  DFFQXLLVT \fifo_mem_reg[0][8] (.CK (clk), .D (n_250), .Q
       (\fifo_mem[0] [8]));
  DFFQXLLVT \fifo_mem_reg[0][9] (.CK (clk), .D (n_251), .Q
       (\fifo_mem[0] [9]));
  DFFQXLLVT \fifo_mem_reg[0][10] (.CK (clk), .D (n_252), .Q
       (\fifo_mem[0] [10]));
  DFFQXLLVT \fifo_mem_reg[0][11] (.CK (clk), .D (n_253), .Q
       (\fifo_mem[0] [11]));
  DFFQXLLVT \fifo_mem_reg[0][12] (.CK (clk), .D (n_254), .Q
       (\fifo_mem[0] [12]));
  DFFQXLLVT \fifo_mem_reg[0][13] (.CK (clk), .D (n_255), .Q
       (\fifo_mem[0] [13]));
  DFFQXLLVT \fifo_mem_reg[0][14] (.CK (clk), .D (n_256), .Q
       (\fifo_mem[0] [14]));
  DFFQXLLVT \fifo_mem_reg[0][15] (.CK (clk), .D (n_257), .Q
       (\fifo_mem[0] [15]));
  NAND2X1LVT g5074__5107(.A (n_43), .B (n_241), .Y (n_284));
  NAND2X1LVT g5068__6260(.A (n_51), .B (n_235), .Y (n_283));
  NAND2X1LVT g5076__4319(.A (n_44), .B (n_247), .Y (n_282));
  NAND2X1LVT g5077__8428(.A (n_40), .B (n_243), .Y (n_281));
  NAND2X1LVT g5078__5526(.A (n_45), .B (n_268), .Y (n_280));
  NAND2X1LVT g5069__6783(.A (n_48), .B (n_269), .Y (n_279));
  NAND2X1LVT g5079__3680(.A (n_50), .B (n_236), .Y (n_278));
  NAND2X1LVT g5080__1617(.A (n_55), .B (n_238), .Y (n_277));
  NAND2X1LVT g5067__2802(.A (n_54), .B (n_265), .Y (n_276));
  NAND2X1LVT g5070__1705(.A (n_53), .B (n_234), .Y (n_275));
  NAND2X1LVT g5081__5122(.A (n_52), .B (n_237), .Y (n_274));
  NAND2X1LVT g5082__8246(.A (n_42), .B (n_245), .Y (n_273));
  NAND2X1LVT g5071__7098(.A (n_49), .B (n_262), .Y (n_272));
  NAND2X1LVT g5072__6131(.A (n_47), .B (n_233), .Y (n_271));
  NAND2X1LVT g5073__1881(.A (n_46), .B (n_264), .Y (n_270));
  DFFQXLLVT \fifo_mem_reg[0][0] (.CK (clk), .D (n_259), .Q
       (\fifo_mem[0] [0]));
  DFFQXLLVT \fifo_mem_reg[4][4] (.CK (clk), .D (n_222), .Q
       (\fifo_mem[4] [4]));
  DFFQXLLVT \fifo_mem_reg[4][1] (.CK (clk), .D (n_223), .Q
       (\fifo_mem[4] [1]));
  DFFQXLLVT \fifo_mem_reg[4][2] (.CK (clk), .D (n_220), .Q
       (\fifo_mem[4] [2]));
  DFFQXLLVT \fifo_mem_reg[4][3] (.CK (clk), .D (n_221), .Q
       (\fifo_mem[4] [3]));
  DFFQXLLVT \fifo_mem_reg[4][0] (.CK (clk), .D (n_218), .Q
       (\fifo_mem[4] [0]));
  DFFQXLLVT \fifo_mem_reg[4][5] (.CK (clk), .D (n_219), .Q
       (\fifo_mem[4] [5]));
  DFFQXLLVT \fifo_mem_reg[4][6] (.CK (clk), .D (n_224), .Q
       (\fifo_mem[4] [6]));
  DFFQXLLVT \fifo_mem_reg[4][7] (.CK (clk), .D (n_226), .Q
       (\fifo_mem[4] [7]));
  DFFQXLLVT \fifo_mem_reg[4][12] (.CK (clk), .D (n_227), .Q
       (\fifo_mem[4] [12]));
  DFFQXLLVT \fifo_mem_reg[4][9] (.CK (clk), .D (n_228), .Q
       (\fifo_mem[4] [9]));
  DFFQXLLVT \fifo_mem_reg[4][10] (.CK (clk), .D (n_229), .Q
       (\fifo_mem[4] [10]));
  DFFQXLLVT \fifo_mem_reg[4][11] (.CK (clk), .D (n_231), .Q
       (\fifo_mem[4] [11]));
  DFFQXLLVT \fifo_mem_reg[4][8] (.CK (clk), .D (n_232), .Q
       (\fifo_mem[4] [8]));
  DFFQXLLVT \fifo_mem_reg[4][13] (.CK (clk), .D (n_225), .Q
       (\fifo_mem[4] [13]));
  DFFQXLLVT \fifo_mem_reg[4][14] (.CK (clk), .D (n_216), .Q
       (\fifo_mem[4] [14]));
  DFFQXLLVT \fifo_mem_reg[4][15] (.CK (clk), .D (n_217), .Q
       (\fifo_mem[4] [15]));
  AOI221X1LVT g5118__5115(.A0 (dout[8]), .A1 (n_267), .B0
       (\fifo_mem[2] [8]), .B1 (n_266), .C0 (n_111), .Y (n_269));
  AOI221X1LVT g5120__7482(.A0 (dout[13]), .A1 (n_267), .B0
       (\fifo_mem[2] [13]), .B1 (n_266), .C0 (n_103), .Y (n_268));
  AOI221X1LVT g5119__4733(.A0 (dout[3]), .A1 (n_267), .B0
       (\fifo_mem[1] [3]), .B1 (n_246), .C0 (n_108), .Y (n_265));
  AOI221X1LVT g5121__6161(.A0 (dout[4]), .A1 (n_267), .B0
       (\fifo_mem[2] [4]), .B1 (n_266), .C0 (n_105), .Y (n_264));
  DFFQXLLVT \fifo_mem_reg[2][14] (.CK (clk), .D (n_200), .Q
       (\fifo_mem[2] [14]));
  DFFQXLLVT \fifo_mem_reg[1][0] (.CK (clk), .D (n_182), .Q
       (\fifo_mem[1] [0]));
  DFFQXLLVT \fifo_mem_reg[1][1] (.CK (clk), .D (n_197), .Q
       (\fifo_mem[1] [1]));
  DFFQXLLVT \fifo_mem_reg[1][2] (.CK (clk), .D (n_195), .Q
       (\fifo_mem[1] [2]));
  DFFQXLLVT \fifo_mem_reg[1][3] (.CK (clk), .D (n_194), .Q
       (\fifo_mem[1] [3]));
  DFFQXLLVT \fifo_mem_reg[1][4] (.CK (clk), .D (n_193), .Q
       (\fifo_mem[1] [4]));
  DFFQXLLVT \fifo_mem_reg[1][6] (.CK (clk), .D (n_191), .Q
       (\fifo_mem[1] [6]));
  DFFQXLLVT \fifo_mem_reg[1][7] (.CK (clk), .D (n_190), .Q
       (\fifo_mem[1] [7]));
  DFFQXLLVT \fifo_mem_reg[1][8] (.CK (clk), .D (n_189), .Q
       (\fifo_mem[1] [8]));
  DFFQXLLVT \fifo_mem_reg[2][9] (.CK (clk), .D (n_205), .Q
       (\fifo_mem[2] [9]));
  DFFQXLLVT \fifo_mem_reg[1][10] (.CK (clk), .D (n_187), .Q
       (\fifo_mem[1] [10]));
  DFFQXLLVT \fifo_mem_reg[1][11] (.CK (clk), .D (n_186), .Q
       (\fifo_mem[1] [11]));
  DFFQXLLVT \fifo_mem_reg[1][12] (.CK (clk), .D (n_185), .Q
       (\fifo_mem[1] [12]));
  DFFQXLLVT \fifo_mem_reg[1][13] (.CK (clk), .D (n_184), .Q
       (\fifo_mem[1] [13]));
  DFFQXLLVT \fifo_mem_reg[1][14] (.CK (clk), .D (n_183), .Q
       (\fifo_mem[1] [14]));
  DFFQXLLVT \fifo_mem_reg[1][15] (.CK (clk), .D (n_198), .Q
       (\fifo_mem[1] [15]));
  DFFQXLLVT \fifo_mem_reg[2][0] (.CK (clk), .D (n_199), .Q
       (\fifo_mem[2] [0]));
  DFFQXLLVT \fifo_mem_reg[2][2] (.CK (clk), .D (n_212), .Q
       (\fifo_mem[2] [2]));
  DFFQXLLVT \fifo_mem_reg[2][3] (.CK (clk), .D (n_211), .Q
       (\fifo_mem[2] [3]));
  DFFQXLLVT \fifo_mem_reg[2][4] (.CK (clk), .D (n_210), .Q
       (\fifo_mem[2] [4]));
  DFFQXLLVT \fifo_mem_reg[2][6] (.CK (clk), .D (n_208), .Q
       (\fifo_mem[2] [6]));
  DFFQXLLVT \fifo_mem_reg[2][7] (.CK (clk), .D (n_207), .Q
       (\fifo_mem[2] [7]));
  DFFQXLLVT \fifo_mem_reg[2][8] (.CK (clk), .D (n_206), .Q
       (\fifo_mem[2] [8]));
  DFFQXLLVT \fifo_mem_reg[2][10] (.CK (clk), .D (n_204), .Q
       (\fifo_mem[2] [10]));
  DFFQXLLVT \fifo_mem_reg[2][11] (.CK (clk), .D (n_203), .Q
       (\fifo_mem[2] [11]));
  DFFQXLLVT \fifo_mem_reg[2][12] (.CK (clk), .D (n_202), .Q
       (\fifo_mem[2] [12]));
  DFFQXLLVT \fifo_mem_reg[2][15] (.CK (clk), .D (n_215), .Q
       (\fifo_mem[2] [15]));
  DFFQXLLVT \fifo_mem_reg[2][13] (.CK (clk), .D (n_201), .Q
       (\fifo_mem[2] [13]));
  MX2XLLVT g5224__9315(.A (\fifo_mem[0] [5]), .B (din[5]), .S0 (n_260),
       .Y (n_263));
  AOI221X1LVT g5117__9945(.A0 (dout[2]), .A1 (n_267), .B0
       (\fifo_mem[2] [2]), .B1 (n_266), .C0 (n_112), .Y (n_262));
  MX2XLLVT g5212__2883(.A (\fifo_mem[0] [1]), .B (din[1]), .S0 (n_260),
       .Y (n_261));
  MX2XLLVT g5213__2346(.A (\fifo_mem[0] [0]), .B (din[0]), .S0 (n_260),
       .Y (n_259));
  MX2XLLVT g5195__1666(.A (\fifo_mem[0] [2]), .B (din[2]), .S0 (n_260),
       .Y (n_258));
  MX2XLLVT g5214__7410(.A (\fifo_mem[0] [15]), .B (din[15]), .S0
       (n_260), .Y (n_257));
  MX2XLLVT g5215__6417(.A (\fifo_mem[0] [14]), .B (din[14]), .S0
       (n_260), .Y (n_256));
  MX2XLLVT g5216__5477(.A (\fifo_mem[0] [13]), .B (din[13]), .S0
       (n_260), .Y (n_255));
  MX2XLLVT g5217__2398(.A (\fifo_mem[0] [12]), .B (din[12]), .S0
       (n_260), .Y (n_254));
  MX2XLLVT g5218__5107(.A (\fifo_mem[0] [11]), .B (din[11]), .S0
       (n_260), .Y (n_253));
  MX2XLLVT g5219__6260(.A (\fifo_mem[0] [10]), .B (din[10]), .S0
       (n_260), .Y (n_252));
  MX2XLLVT g5220__4319(.A (\fifo_mem[0] [9]), .B (din[9]), .S0 (n_260),
       .Y (n_251));
  MX2XLLVT g5221__8428(.A (\fifo_mem[0] [8]), .B (din[8]), .S0 (n_260),
       .Y (n_250));
  MX2XLLVT g5222__5526(.A (\fifo_mem[0] [7]), .B (din[7]), .S0 (n_260),
       .Y (n_249));
  MX2XLLVT g5223__6783(.A (\fifo_mem[0] [6]), .B (din[6]), .S0 (n_260),
       .Y (n_248));
  AOI221X1LVT g5116__3680(.A0 (\fifo_mem[1] [12]), .A1 (n_246), .B0
       (\fifo_mem[0] [12]), .B1 (n_244), .C0 (n_104), .Y (n_247));
  AOI221X1LVT g5122__1617(.A0 (\fifo_mem[2] [1]), .A1 (n_266), .B0
       (\fifo_mem[0] [1]), .B1 (n_244), .C0 (n_100), .Y (n_245));
  AOI221X1LVT g5107__2802(.A0 (dout[5]), .A1 (n_267), .B0
       (\fifo_mem[2] [5]), .B1 (n_266), .C0 (n_102), .Y (n_243));
  MX2XLLVT g5225__1705(.A (\fifo_mem[0] [4]), .B (din[4]), .S0 (n_260),
       .Y (n_242));
  AOI221X1LVT g5115__5122(.A0 (\fifo_mem[1] [11]), .A1 (n_246), .B0
       (\fifo_mem[0] [11]), .B1 (n_244), .C0 (n_106), .Y (n_241));
  MX2XLLVT g5226__8246(.A (\fifo_mem[0] [3]), .B (din[3]), .S0 (n_260),
       .Y (n_240));
  AOI221X1LVT g5108__7098(.A0 (\fifo_mem[2] [14]), .A1 (n_266), .B0
       (\fifo_mem[0] [14]), .B1 (n_244), .C0 (n_101), .Y (n_239));
  AOI221X1LVT g5109__6131(.A0 (\fifo_mem[2] [15]), .A1 (n_266), .B0
       (\fifo_mem[0] [15]), .B1 (n_244), .C0 (n_99), .Y (n_238));
  AOI221X1LVT g5110__1881(.A0 (\fifo_mem[2] [6]), .A1 (n_266), .B0
       (\fifo_mem[0] [6]), .B1 (n_244), .C0 (n_98), .Y (n_237));
  AOI221X1LVT g5111__5115(.A0 (\fifo_mem[1] [0]), .A1 (n_246), .B0
       (\fifo_mem[0] [0]), .B1 (n_244), .C0 (n_110), .Y (n_236));
  AOI221X1LVT g5112__7482(.A0 (\fifo_mem[1] [7]), .A1 (n_246), .B0
       (\fifo_mem[0] [7]), .B1 (n_244), .C0 (n_172), .Y (n_235));
  AOI221X1LVT g5113__4733(.A0 (\fifo_mem[1] [9]), .A1 (n_246), .B0
       (\fifo_mem[0] [9]), .B1 (n_244), .C0 (n_109), .Y (n_234));
  AOI221X1LVT g5114__6161(.A0 (\fifo_mem[1] [10]), .A1 (n_246), .B0
       (\fifo_mem[0] [10]), .B1 (n_244), .C0 (n_107), .Y (n_233));
  DFFQXLLVT \fifo_mem_reg[2][1] (.CK (clk), .D (n_214), .Q
       (\fifo_mem[2] [1]));
  DFFQXLLVT \fifo_mem_reg[1][9] (.CK (clk), .D (n_188), .Q
       (\fifo_mem[1] [9]));
  DFFQXLLVT \fifo_mem_reg[1][5] (.CK (clk), .D (n_192), .Q
       (\fifo_mem[1] [5]));
  DFFQXLLVT \fifo_mem_reg[2][5] (.CK (clk), .D (n_209), .Q
       (\fifo_mem[2] [5]));
  MX2XLLVT g5203__9315(.A (\fifo_mem[4] [8]), .B (din[8]), .S0 (n_230),
       .Y (n_232));
  MX2XLLVT g5200__9945(.A (\fifo_mem[4] [11]), .B (din[11]), .S0
       (n_230), .Y (n_231));
  MX2XLLVT g5201__2883(.A (\fifo_mem[4] [10]), .B (din[10]), .S0
       (n_230), .Y (n_229));
  MX2XLLVT g5202__2346(.A (\fifo_mem[4] [9]), .B (din[9]), .S0 (n_230),
       .Y (n_228));
  MX2XLLVT g5199__1666(.A (\fifo_mem[4] [12]), .B (din[12]), .S0
       (n_230), .Y (n_227));
  MX2XLLVT g5204__7410(.A (\fifo_mem[4] [7]), .B (din[7]), .S0 (n_230),
       .Y (n_226));
  MX2XLLVT g5198__6417(.A (\fifo_mem[4] [13]), .B (din[13]), .S0
       (n_230), .Y (n_225));
  MX2XLLVT g5205__5477(.A (\fifo_mem[4] [6]), .B (din[6]), .S0 (n_230),
       .Y (n_224));
  DFFQXLLVT \fifo_mem_reg[6][11] (.CK (clk), .D (n_134), .Q
       (\fifo_mem[6] [11]));
  DFFQXLLVT \fifo_mem_reg[7][11] (.CK (clk), .D (n_117), .Q
       (\fifo_mem[7] [11]));
  DFFQXLLVT \fifo_mem_reg[5][13] (.CK (clk), .D (n_155), .Q
       (\fifo_mem[5] [13]));
  DFFQXLLVT \fifo_mem_reg[5][5] (.CK (clk), .D (n_163), .Q
       (\fifo_mem[5] [5]));
  DFFQXLLVT \fifo_mem_reg[5][9] (.CK (clk), .D (n_181), .Q
       (\fifo_mem[5] [9]));
  DFFQXLLVT \fifo_mem_reg[3][5] (.CK (clk), .D (n_175), .Q
       (\fifo_mem[3] [5]));
  DFFQXLLVT \fifo_mem_reg[3][1] (.CK (clk), .D (n_180), .Q
       (\fifo_mem[3] [1]));
  DFFQXLLVT \fifo_mem_reg[7][15] (.CK (clk), .D (n_152), .Q
       (\fifo_mem[7] [15]));
  DFFQXLLVT \fifo_mem_reg[6][3] (.CK (clk), .D (n_143), .Q
       (\fifo_mem[6] [3]));
  DFFQXLLVT \fifo_mem_reg[7][14] (.CK (clk), .D (n_150), .Q
       (\fifo_mem[7] [14]));
  DFFQXLLVT \fifo_mem_reg[3][0] (.CK (clk), .D (n_159), .Q
       (\fifo_mem[3] [0]));
  DFFQXLLVT \fifo_mem_reg[3][2] (.CK (clk), .D (n_179), .Q
       (\fifo_mem[3] [2]));
  DFFQXLLVT \fifo_mem_reg[6][7] (.CK (clk), .D (n_138), .Q
       (\fifo_mem[6] [7]));
  DFFQXLLVT \fifo_mem_reg[3][3] (.CK (clk), .D (n_177), .Q
       (\fifo_mem[3] [3]));
  DFFQXLLVT \fifo_mem_reg[3][4] (.CK (clk), .D (n_176), .Q
       (\fifo_mem[3] [4]));
  DFFQXLLVT \fifo_mem_reg[3][6] (.CK (clk), .D (n_174), .Q
       (\fifo_mem[3] [6]));
  DFFQXLLVT \fifo_mem_reg[3][7] (.CK (clk), .D (n_113), .Q
       (\fifo_mem[3] [7]));
  DFFQXLLVT \fifo_mem_reg[3][8] (.CK (clk), .D (n_115), .Q
       (\fifo_mem[3] [8]));
  DFFQXLLVT \fifo_mem_reg[3][10] (.CK (clk), .D (n_123), .Q
       (\fifo_mem[3] [10]));
  DFFQXLLVT \fifo_mem_reg[3][11] (.CK (clk), .D (n_142), .Q
       (\fifo_mem[3] [11]));
  DFFQXLLVT \fifo_mem_reg[3][12] (.CK (clk), .D (n_126), .Q
       (\fifo_mem[3] [12]));
  DFFQXLLVT \fifo_mem_reg[3][13] (.CK (clk), .D (n_114), .Q
       (\fifo_mem[3] [13]));
  DFFQXLLVT \fifo_mem_reg[3][14] (.CK (clk), .D (n_148), .Q
       (\fifo_mem[3] [14]));
  DFFQXLLVT \fifo_mem_reg[3][15] (.CK (clk), .D (n_173), .Q
       (\fifo_mem[3] [15]));
  DFFQXLLVT \fifo_mem_reg[5][0] (.CK (clk), .D (n_169), .Q
       (\fifo_mem[5] [0]));
  DFFQXLLVT \fifo_mem_reg[5][2] (.CK (clk), .D (n_167), .Q
       (\fifo_mem[5] [2]));
  DFFQXLLVT \fifo_mem_reg[5][3] (.CK (clk), .D (n_166), .Q
       (\fifo_mem[5] [3]));
  DFFQXLLVT \fifo_mem_reg[5][4] (.CK (clk), .D (n_165), .Q
       (\fifo_mem[5] [4]));
  DFFQXLLVT \fifo_mem_reg[5][6] (.CK (clk), .D (n_162), .Q
       (\fifo_mem[5] [6]));
  DFFQXLLVT \fifo_mem_reg[5][7] (.CK (clk), .D (n_161), .Q
       (\fifo_mem[5] [7]));
  DFFQXLLVT \fifo_mem_reg[5][8] (.CK (clk), .D (n_160), .Q
       (\fifo_mem[5] [8]));
  DFFQXLLVT \fifo_mem_reg[7][7] (.CK (clk), .D (n_120), .Q
       (\fifo_mem[7] [7]));
  MX2XLLVT g5210__2398(.A (\fifo_mem[4] [1]), .B (din[1]), .S0 (n_230),
       .Y (n_223));
  MX2XLLVT g5207__5107(.A (\fifo_mem[4] [4]), .B (din[4]), .S0 (n_230),
       .Y (n_222));
  MX2XLLVT g5208__6260(.A (\fifo_mem[4] [3]), .B (din[3]), .S0 (n_230),
       .Y (n_221));
  MX2XLLVT g5209__4319(.A (\fifo_mem[4] [2]), .B (din[2]), .S0 (n_230),
       .Y (n_220));
  MX2XLLVT g5206__8428(.A (\fifo_mem[4] [5]), .B (din[5]), .S0 (n_230),
       .Y (n_219));
  MX2XLLVT g5211__5526(.A (\fifo_mem[4] [0]), .B (din[0]), .S0 (n_230),
       .Y (n_218));
  MX2XLLVT g5196__6783(.A (\fifo_mem[4] [15]), .B (din[15]), .S0
       (n_230), .Y (n_217));
  MX2XLLVT g5197__3680(.A (\fifo_mem[4] [14]), .B (din[14]), .S0
       (n_230), .Y (n_216));
  DFFQXLLVT \fifo_mem_reg[7][8] (.CK (clk), .D (n_119), .Q
       (\fifo_mem[7] [8]));
  DFFQXLLVT \fifo_mem_reg[7][6] (.CK (clk), .D (n_121), .Q
       (\fifo_mem[7] [6]));
  DFFQXLLVT \fifo_mem_reg[7][5] (.CK (clk), .D (n_122), .Q
       (\fifo_mem[7] [5]));
  DFFQXLLVT \fifo_mem_reg[7][4] (.CK (clk), .D (n_124), .Q
       (\fifo_mem[7] [4]));
  DFFQXLLVT \fifo_mem_reg[7][2] (.CK (clk), .D (n_127), .Q
       (\fifo_mem[7] [2]));
  DFFQXLLVT \fifo_mem_reg[7][1] (.CK (clk), .D (n_128), .Q
       (\fifo_mem[7] [1]));
  DFFQXLLVT \fifo_mem_reg[7][0] (.CK (clk), .D (n_129), .Q
       (\fifo_mem[7] [0]));
  DFFQXLLVT \fifo_mem_reg[5][14] (.CK (clk), .D (n_154), .Q
       (\fifo_mem[5] [14]));
  DFFQXLLVT \fifo_mem_reg[6][13] (.CK (clk), .D (n_132), .Q
       (\fifo_mem[6] [13]));
  DFFQXLLVT \fifo_mem_reg[6][12] (.CK (clk), .D (n_133), .Q
       (\fifo_mem[6] [12]));
  DFFQXLLVT \fifo_mem_reg[6][9] (.CK (clk), .D (n_136), .Q
       (\fifo_mem[6] [9]));
  DFFQXLLVT \fifo_mem_reg[6][10] (.CK (clk), .D (n_135), .Q
       (\fifo_mem[6] [10]));
  DFFQXLLVT \fifo_mem_reg[5][10] (.CK (clk), .D (n_158), .Q
       (\fifo_mem[5] [10]));
  DFFQXLLVT \fifo_mem_reg[6][8] (.CK (clk), .D (n_137), .Q
       (\fifo_mem[6] [8]));
  DFFQXLLVT \fifo_mem_reg[6][6] (.CK (clk), .D (n_139), .Q
       (\fifo_mem[6] [6]));
  DFFQXLLVT \fifo_mem_reg[6][5] (.CK (clk), .D (n_140), .Q
       (\fifo_mem[6] [5]));
  DFFQXLLVT \fifo_mem_reg[6][4] (.CK (clk), .D (n_141), .Q
       (\fifo_mem[6] [4]));
  DFFQXLLVT \fifo_mem_reg[6][2] (.CK (clk), .D (n_144), .Q
       (\fifo_mem[6] [2]));
  DFFQXLLVT \fifo_mem_reg[6][1] (.CK (clk), .D (n_146), .Q
       (\fifo_mem[6] [1]));
  DFFQXLLVT \fifo_mem_reg[6][0] (.CK (clk), .D (n_147), .Q
       (\fifo_mem[6] [0]));
  DFFQXLLVT \fifo_mem_reg[5][15] (.CK (clk), .D (n_153), .Q
       (\fifo_mem[5] [15]));
  DFFQXLLVT \fifo_mem_reg[5][11] (.CK (clk), .D (n_157), .Q
       (\fifo_mem[5] [11]));
  DFFQXLLVT \fifo_mem_reg[5][12] (.CK (clk), .D (n_156), .Q
       (\fifo_mem[5] [12]));
  DFFQXLLVT \fifo_mem_reg[6][14] (.CK (clk), .D (n_131), .Q
       (\fifo_mem[6] [14]));
  DFFQXLLVT \fifo_mem_reg[7][13] (.CK (clk), .D (n_171), .Q
       (\fifo_mem[7] [13]));
  DFFQXLLVT \fifo_mem_reg[7][12] (.CK (clk), .D (n_116), .Q
       (\fifo_mem[7] [12]));
  DFFQXLLVT \fifo_mem_reg[5][1] (.CK (clk), .D (n_164), .Q
       (\fifo_mem[5] [1]));
  DFFQXLLVT \fifo_mem_reg[6][15] (.CK (clk), .D (n_130), .Q
       (\fifo_mem[6] [15]));
  DFFQXLLVT \fifo_mem_reg[3][9] (.CK (clk), .D (n_170), .Q
       (\fifo_mem[3] [9]));
  DFFQXLLVT \fifo_mem_reg[7][3] (.CK (clk), .D (n_125), .Q
       (\fifo_mem[7] [3]));
  DFFQXLLVT \fifo_mem_reg[7][10] (.CK (clk), .D (n_149), .Q
       (\fifo_mem[7] [10]));
  DFFQXLLVT \fifo_mem_reg[7][9] (.CK (clk), .D (n_118), .Q
       (\fifo_mem[7] [9]));
  MX2XLLVT g5290__1617(.A (din[15]), .B (\fifo_mem[2] [15]), .S0
       (n_213), .Y (n_215));
  MX2XLLVT g5276__2802(.A (din[1]), .B (\fifo_mem[2] [1]), .S0 (n_213),
       .Y (n_214));
  MX2XLLVT g5277__1705(.A (din[2]), .B (\fifo_mem[2] [2]), .S0 (n_213),
       .Y (n_212));
  MX2XLLVT g5278__5122(.A (din[3]), .B (\fifo_mem[2] [3]), .S0 (n_213),
       .Y (n_211));
  MX2XLLVT g5279__8246(.A (din[4]), .B (\fifo_mem[2] [4]), .S0 (n_213),
       .Y (n_210));
  MX2XLLVT g5280__7098(.A (din[5]), .B (\fifo_mem[2] [5]), .S0 (n_213),
       .Y (n_209));
  MX2XLLVT g5281__6131(.A (din[6]), .B (\fifo_mem[2] [6]), .S0 (n_213),
       .Y (n_208));
  MX2XLLVT g5282__1881(.A (din[7]), .B (\fifo_mem[2] [7]), .S0 (n_213),
       .Y (n_207));
  MX2XLLVT g5283__5115(.A (din[8]), .B (\fifo_mem[2] [8]), .S0 (n_213),
       .Y (n_206));
  MX2XLLVT g5284__7482(.A (din[9]), .B (\fifo_mem[2] [9]), .S0 (n_213),
       .Y (n_205));
  MX2XLLVT g5285__4733(.A (din[10]), .B (\fifo_mem[2] [10]), .S0
       (n_213), .Y (n_204));
  MX2XLLVT g5286__6161(.A (din[11]), .B (\fifo_mem[2] [11]), .S0
       (n_213), .Y (n_203));
  MX2XLLVT g5287__9315(.A (din[12]), .B (\fifo_mem[2] [12]), .S0
       (n_213), .Y (n_202));
  MX2XLLVT g5288__9945(.A (din[13]), .B (\fifo_mem[2] [13]), .S0
       (n_213), .Y (n_201));
  MX2XLLVT g5289__2883(.A (din[14]), .B (\fifo_mem[2] [14]), .S0
       (n_213), .Y (n_200));
  MX2XLLVT g5275__2346(.A (din[0]), .B (\fifo_mem[2] [0]), .S0 (n_213),
       .Y (n_199));
  MX2XLLVT g5306__1666(.A (din[15]), .B (\fifo_mem[1] [15]), .S0
       (n_196), .Y (n_198));
  MX2XLLVT g5292__7410(.A (din[1]), .B (\fifo_mem[1] [1]), .S0 (n_196),
       .Y (n_197));
  MX2XLLVT g5293__6417(.A (din[2]), .B (\fifo_mem[1] [2]), .S0 (n_196),
       .Y (n_195));
  MX2XLLVT g5294__5477(.A (din[3]), .B (\fifo_mem[1] [3]), .S0 (n_196),
       .Y (n_194));
  MX2XLLVT g5295__2398(.A (din[4]), .B (\fifo_mem[1] [4]), .S0 (n_196),
       .Y (n_193));
  MX2XLLVT g5296__5107(.A (din[5]), .B (\fifo_mem[1] [5]), .S0 (n_196),
       .Y (n_192));
  MX2XLLVT g5297__6260(.A (din[6]), .B (\fifo_mem[1] [6]), .S0 (n_196),
       .Y (n_191));
  MX2XLLVT g5298__4319(.A (din[7]), .B (\fifo_mem[1] [7]), .S0 (n_196),
       .Y (n_190));
  MX2XLLVT g5299__8428(.A (din[8]), .B (\fifo_mem[1] [8]), .S0 (n_196),
       .Y (n_189));
  MX2XLLVT g5300__5526(.A (din[9]), .B (\fifo_mem[1] [9]), .S0 (n_196),
       .Y (n_188));
  MX2XLLVT g5301__6783(.A (din[10]), .B (\fifo_mem[1] [10]), .S0
       (n_196), .Y (n_187));
  MX2XLLVT g5302__3680(.A (din[11]), .B (\fifo_mem[1] [11]), .S0
       (n_196), .Y (n_186));
  MX2XLLVT g5303__1617(.A (din[12]), .B (\fifo_mem[1] [12]), .S0
       (n_196), .Y (n_185));
  MX2XLLVT g5304__2802(.A (din[13]), .B (\fifo_mem[1] [13]), .S0
       (n_196), .Y (n_184));
  MX2XLLVT g5305__1705(.A (din[14]), .B (\fifo_mem[1] [14]), .S0
       (n_196), .Y (n_183));
  MX2XLLVT g5291__5122(.A (din[0]), .B (\fifo_mem[1] [0]), .S0 (n_196),
       .Y (n_182));
  MX2XLLVT g5332__8246(.A (\fifo_mem[5] [9]), .B (din[9]), .S0 (n_292),
       .Y (n_181));
  MX2XLLVT g5308__7098(.A (\fifo_mem[3] [1]), .B (din[1]), .S0 (n_178),
       .Y (n_180));
  MX2XLLVT g5309__6131(.A (\fifo_mem[3] [2]), .B (din[2]), .S0 (n_178),
       .Y (n_179));
  MX2XLLVT g5310__1881(.A (\fifo_mem[3] [3]), .B (din[3]), .S0 (n_178),
       .Y (n_177));
  MX2XLLVT g5311__5115(.A (\fifo_mem[3] [4]), .B (din[4]), .S0 (n_178),
       .Y (n_176));
  MX2XLLVT g5312__7482(.A (\fifo_mem[3] [5]), .B (din[5]), .S0 (n_178),
       .Y (n_175));
  MX2XLLVT g5313__4733(.A (\fifo_mem[3] [6]), .B (din[6]), .S0 (n_178),
       .Y (n_174));
  MX2XLLVT g5322__6161(.A (\fifo_mem[3] [15]), .B (din[15]), .S0
       (n_178), .Y (n_173));
  NAND2X1LVT g5314__9315(.A (n_71), .B (n_91), .Y (n_172));
  MX2XLLVT g5315__9945(.A (\fifo_mem[7] [13]), .B (din[13]), .S0
       (n_151), .Y (n_171));
  MX2XLLVT g5316__2883(.A (\fifo_mem[3] [9]), .B (din[9]), .S0 (n_178),
       .Y (n_170));
  MX2XLLVT g5323__2346(.A (\fifo_mem[5] [0]), .B (din[0]), .S0 (n_292),
       .Y (n_169));
  MX2XLLVT g5325__1666(.A (\fifo_mem[5] [2]), .B (din[2]), .S0 (n_292),
       .Y (n_167));
  MX2XLLVT g5326__7410(.A (\fifo_mem[5] [3]), .B (din[3]), .S0 (n_292),
       .Y (n_166));
  MX2XLLVT g5327__6417(.A (\fifo_mem[5] [4]), .B (din[4]), .S0 (n_292),
       .Y (n_165));
  MX2XLLVT g5324__5477(.A (\fifo_mem[5] [1]), .B (din[1]), .S0 (n_292),
       .Y (n_164));
  MX2XLLVT g5328__2398(.A (\fifo_mem[5] [5]), .B (din[5]), .S0 (n_292),
       .Y (n_163));
  MX2XLLVT g5329__5107(.A (\fifo_mem[5] [6]), .B (din[6]), .S0 (n_292),
       .Y (n_162));
  MX2XLLVT g5330__6260(.A (\fifo_mem[5] [7]), .B (din[7]), .S0 (n_292),
       .Y (n_161));
  MX2XLLVT g5331__4319(.A (\fifo_mem[5] [8]), .B (din[8]), .S0 (n_292),
       .Y (n_160));
  MX2XLLVT g5307__8428(.A (\fifo_mem[3] [0]), .B (din[0]), .S0 (n_178),
       .Y (n_159));
  MX2XLLVT g5333__5526(.A (\fifo_mem[5] [10]), .B (din[10]), .S0
       (n_292), .Y (n_158));
  MX2XLLVT g5334__6783(.A (\fifo_mem[5] [11]), .B (din[11]), .S0
       (n_292), .Y (n_157));
  MX2XLLVT g5335__3680(.A (\fifo_mem[5] [12]), .B (din[12]), .S0
       (n_292), .Y (n_156));
  MX2XLLVT g5336__1617(.A (\fifo_mem[5] [13]), .B (din[13]), .S0
       (n_292), .Y (n_155));
  MX2XLLVT g5337__2802(.A (\fifo_mem[5] [14]), .B (din[14]), .S0
       (n_292), .Y (n_154));
  MX2XLLVT g5338__1705(.A (\fifo_mem[5] [15]), .B (din[15]), .S0
       (n_292), .Y (n_153));
  MX2XLLVT g5339__5122(.A (\fifo_mem[7] [15]), .B (din[15]), .S0
       (n_151), .Y (n_152));
  MX2XLLVT g5340__8246(.A (\fifo_mem[7] [14]), .B (din[14]), .S0
       (n_151), .Y (n_150));
  MX2XLLVT g5341__7098(.A (\fifo_mem[7] [10]), .B (din[10]), .S0
       (n_151), .Y (n_149));
  MX2XLLVT g5321__6131(.A (\fifo_mem[3] [14]), .B (din[14]), .S0
       (n_178), .Y (n_148));
  MX2XLLVT g5342__1881(.A (\fifo_mem[6] [0]), .B (din[0]), .S0 (n_293),
       .Y (n_147));
  MX2XLLVT g5343__5115(.A (\fifo_mem[6] [1]), .B (din[1]), .S0 (n_293),
       .Y (n_146));
  MX2XLLVT g5344__7482(.A (\fifo_mem[6] [2]), .B (din[2]), .S0 (n_293),
       .Y (n_144));
  MX2XLLVT g5345__4733(.A (\fifo_mem[6] [3]), .B (din[3]), .S0 (n_293),
       .Y (n_143));
  MX2XLLVT g5318__6161(.A (\fifo_mem[3] [11]), .B (din[11]), .S0
       (n_178), .Y (n_142));
  MX2XLLVT g5346__9315(.A (\fifo_mem[6] [4]), .B (din[4]), .S0 (n_293),
       .Y (n_141));
  MX2XLLVT g5347__9945(.A (\fifo_mem[6] [5]), .B (din[5]), .S0 (n_293),
       .Y (n_140));
  MX2XLLVT g5348__2883(.A (\fifo_mem[6] [6]), .B (din[6]), .S0 (n_293),
       .Y (n_139));
  MX2XLLVT g5349__2346(.A (\fifo_mem[6] [7]), .B (din[7]), .S0 (n_293),
       .Y (n_138));
  MX2XLLVT g5350__1666(.A (\fifo_mem[6] [8]), .B (din[8]), .S0 (n_293),
       .Y (n_137));
  MX2XLLVT g5351__7410(.A (\fifo_mem[6] [9]), .B (din[9]), .S0 (n_293),
       .Y (n_136));
  MX2XLLVT g5352__6417(.A (\fifo_mem[6] [10]), .B (din[10]), .S0
       (n_293), .Y (n_135));
  MX2XLLVT g5353__5477(.A (\fifo_mem[6] [11]), .B (din[11]), .S0
       (n_293), .Y (n_134));
  MX2XLLVT g5354__2398(.A (\fifo_mem[6] [12]), .B (din[12]), .S0
       (n_293), .Y (n_133));
  MX2XLLVT g5355__5107(.A (\fifo_mem[6] [13]), .B (din[13]), .S0
       (n_293), .Y (n_132));
  MX2XLLVT g5356__6260(.A (\fifo_mem[6] [14]), .B (din[14]), .S0
       (n_293), .Y (n_131));
  MX2XLLVT g5357__4319(.A (\fifo_mem[6] [15]), .B (din[15]), .S0
       (n_293), .Y (n_130));
  MX2XLLVT g5358__8428(.A (\fifo_mem[7] [0]), .B (din[0]), .S0 (n_151),
       .Y (n_129));
  MX2XLLVT g5359__5526(.A (\fifo_mem[7] [1]), .B (din[1]), .S0 (n_151),
       .Y (n_128));
  MX2XLLVT g5360__6783(.A (\fifo_mem[7] [2]), .B (din[2]), .S0 (n_151),
       .Y (n_127));
  MX2XLLVT g5319__3680(.A (\fifo_mem[3] [12]), .B (din[12]), .S0
       (n_178), .Y (n_126));
  MX2XLLVT g5361__1617(.A (\fifo_mem[7] [3]), .B (din[3]), .S0 (n_151),
       .Y (n_125));
  MX2XLLVT g5362__2802(.A (\fifo_mem[7] [4]), .B (din[4]), .S0 (n_151),
       .Y (n_124));
  MX2XLLVT g5317__1705(.A (\fifo_mem[3] [10]), .B (din[10]), .S0
       (n_178), .Y (n_123));
  MX2XLLVT g5363__5122(.A (\fifo_mem[7] [5]), .B (din[5]), .S0 (n_151),
       .Y (n_122));
  MX2XLLVT g5364__8246(.A (\fifo_mem[7] [6]), .B (din[6]), .S0 (n_151),
       .Y (n_121));
  MX2XLLVT g5365__7098(.A (\fifo_mem[7] [7]), .B (din[7]), .S0 (n_151),
       .Y (n_120));
  MX2XLLVT g5366__6131(.A (\fifo_mem[7] [8]), .B (din[8]), .S0 (n_151),
       .Y (n_119));
  MX2XLLVT g5367__1881(.A (\fifo_mem[7] [9]), .B (din[9]), .S0 (n_151),
       .Y (n_118));
  MX2XLLVT g5368__5115(.A (\fifo_mem[7] [11]), .B (din[11]), .S0
       (n_151), .Y (n_117));
  MX2XLLVT g5369__7482(.A (\fifo_mem[7] [12]), .B (din[12]), .S0
       (n_151), .Y (n_116));
  MX2XLLVT g5370__4733(.A (\fifo_mem[3] [8]), .B (din[8]), .S0 (n_178),
       .Y (n_115));
  MX2XLLVT g5320__6161(.A (\fifo_mem[3] [13]), .B (din[13]), .S0
       (n_178), .Y (n_114));
  MX2XLLVT g5259__9315(.A (\fifo_mem[3] [7]), .B (din[7]), .S0 (n_178),
       .Y (n_113));
  NAND2X1LVT g5260__9945(.A (n_69), .B (n_90), .Y (n_112));
  NAND2X1LVT g5261__2883(.A (n_72), .B (n_97), .Y (n_111));
  NAND2X1LVT g5262__2346(.A (n_64), .B (n_89), .Y (n_110));
  NAND2X1LVT g5263__1666(.A (n_74), .B (n_82), .Y (n_109));
  NAND2X1LVT g5264__7410(.A (n_63), .B (n_79), .Y (n_108));
  NAND2X1LVT g5265__6417(.A (n_60), .B (n_96), .Y (n_107));
  NAND2X1LVT g5266__5477(.A (n_62), .B (n_83), .Y (n_106));
  NAND2X1LVT g5267__2398(.A (n_61), .B (n_81), .Y (n_105));
  NAND2X1LVT g5268__5107(.A (n_68), .B (n_80), .Y (n_104));
  NAND2X1LVT g5269__6260(.A (n_58), .B (n_84), .Y (n_103));
  NAND2X1LVT g5270__4319(.A (n_57), .B (n_78), .Y (n_102));
  NAND2X1LVT g5271__8428(.A (n_59), .B (n_92), .Y (n_101));
  NAND2X1LVT g5272__5526(.A (n_65), .B (n_85), .Y (n_100));
  NAND2X1LVT g5273__6783(.A (n_56), .B (n_77), .Y (n_99));
  NAND2X1LVT g5274__3680(.A (n_70), .B (n_88), .Y (n_98));
  NOR2X1LVT g5380__1617(.A (wptr[0]), .B (n_76), .Y (n_260));
  NOR2BX1LVT g5379__2802(.AN (n_73), .B (wptr[0]), .Y (n_230));
  AOI222X1LVT g5373__1705(.A0 (\fifo_mem[6] [8]), .A1 (n_95), .B0
       (\fifo_mem[7] [8]), .B1 (n_94), .C0 (\fifo_mem[4] [8]), .C1
       (n_93), .Y (n_97));
  AOI222X1LVT g5383__5122(.A0 (\fifo_mem[6] [10]), .A1 (n_95), .B0
       (\fifo_mem[7] [10]), .B1 (n_94), .C0 (\fifo_mem[4] [10]), .C1
       (n_93), .Y (n_96));
  AOI222X1LVT g5382__8246(.A0 (\fifo_mem[6] [14]), .A1 (n_95), .B0
       (\fifo_mem[7] [14]), .B1 (n_94), .C0 (\fifo_mem[4] [14]), .C1
       (n_93), .Y (n_92));
  AOI222X1LVT g5371__7098(.A0 (\fifo_mem[5] [7]), .A1 (n_87), .B0
       (\fifo_mem[6] [7]), .B1 (n_95), .C0 (\fifo_mem[3] [7]), .C1
       (n_291), .Y (n_91));
  AOI222X1LVT g5372__6131(.A0 (\fifo_mem[6] [2]), .A1 (n_95), .B0
       (\fifo_mem[7] [2]), .B1 (n_94), .C0 (\fifo_mem[4] [2]), .C1
       (n_93), .Y (n_90));
  AOI222X1LVT g5381__1881(.A0 (\fifo_mem[6] [0]), .A1 (n_95), .B0
       (\fifo_mem[7] [0]), .B1 (n_94), .C0 (\fifo_mem[4] [0]), .C1
       (n_93), .Y (n_89));
  AOI222X1LVT g5374__5115(.A0 (\fifo_mem[5] [6]), .A1 (n_87), .B0
       (\fifo_mem[6] [6]), .B1 (n_95), .C0 (\fifo_mem[3] [6]), .C1
       (n_291), .Y (n_88));
  AOI222X1LVT g5375__7482(.A0 (\fifo_mem[6] [1]), .A1 (n_95), .B0
       (\fifo_mem[7] [1]), .B1 (n_94), .C0 (\fifo_mem[4] [1]), .C1
       (n_93), .Y (n_85));
  DFFRHQX1LVT \wptr_reg[2] (.RN (rstn), .CK (clk), .D (n_35), .Q
       (wptr[2]));
  AOI222X1LVT g5389__4733(.A0 (\fifo_mem[6] [13]), .A1 (n_95), .B0
       (\fifo_mem[7] [13]), .B1 (n_94), .C0 (\fifo_mem[4] [13]), .C1
       (n_93), .Y (n_84));
  AOI222X1LVT g5385__6161(.A0 (\fifo_mem[6] [11]), .A1 (n_95), .B0
       (\fifo_mem[7] [11]), .B1 (n_94), .C0 (\fifo_mem[4] [11]), .C1
       (n_93), .Y (n_83));
  AOI222X1LVT g5386__9315(.A0 (\fifo_mem[5] [9]), .A1 (n_87), .B0
       (\fifo_mem[6] [9]), .B1 (n_95), .C0 (\fifo_mem[3] [9]), .C1
       (n_291), .Y (n_82));
  AOI222X1LVT g5387__9945(.A0 (\fifo_mem[5] [4]), .A1 (n_87), .B0
       (\fifo_mem[6] [4]), .B1 (n_95), .C0 (\fifo_mem[3] [4]), .C1
       (n_291), .Y (n_81));
  AOI222X1LVT g5388__2883(.A0 (\fifo_mem[6] [12]), .A1 (n_95), .B0
       (\fifo_mem[7] [12]), .B1 (n_94), .C0 (\fifo_mem[4] [12]), .C1
       (n_93), .Y (n_80));
  AOI222X1LVT g5384__2346(.A0 (\fifo_mem[6] [3]), .A1 (n_95), .B0
       (\fifo_mem[7] [3]), .B1 (n_94), .C0 (\fifo_mem[4] [3]), .C1
       (n_93), .Y (n_79));
  AOI222X1LVT g5390__1666(.A0 (\fifo_mem[5] [5]), .A1 (n_87), .B0
       (\fifo_mem[6] [5]), .B1 (n_95), .C0 (\fifo_mem[3] [5]), .C1
       (n_291), .Y (n_78));
  AOI222X1LVT g5391__7410(.A0 (\fifo_mem[6] [15]), .A1 (n_95), .B0
       (\fifo_mem[7] [15]), .B1 (n_94), .C0 (\fifo_mem[4] [15]), .C1
       (n_93), .Y (n_77));
  NAND2X1LVT g5397__6417(.A (n_36), .B (n_75), .Y (n_76));
  NAND2X1LVT g5408__5477(.A (n_6), .B (n_75), .Y (n_196));
  NAND2X1LVT g5407__2398(.A (n_5), .B (n_75), .Y (n_213));
  AOI22X1LVT g5393__5107(.A0 (\fifo_mem[4] [9]), .A1 (n_93), .B0
       (\fifo_mem[7] [9]), .B1 (n_94), .Y (n_74));
  NOR2XLLVT g5394__6260(.A (wptr[1]), .B (n_66), .Y (n_73));
  AOI22X1LVT g5398__4319(.A0 (\fifo_mem[5] [8]), .A1 (n_87), .B0
       (\fifo_mem[3] [8]), .B1 (n_291), .Y (n_72));
  AOI22X1LVT g5403__8428(.A0 (\fifo_mem[4] [7]), .A1 (n_93), .B0
       (\fifo_mem[7] [7]), .B1 (n_94), .Y (n_71));
  AOI22X1LVT g5404__5526(.A0 (\fifo_mem[4] [6]), .A1 (n_93), .B0
       (\fifo_mem[7] [6]), .B1 (n_94), .Y (n_70));
  AOI22X1LVT g5406__6783(.A0 (\fifo_mem[5] [2]), .A1 (n_87), .B0
       (\fifo_mem[3] [2]), .B1 (n_291), .Y (n_69));
  AOI22X1LVT g5413__3680(.A0 (\fifo_mem[5] [12]), .A1 (n_87), .B0
       (\fifo_mem[3] [12]), .B1 (n_291), .Y (n_68));
  NOR2X1LVT g5412__1617(.A (n_67), .B (n_34), .Y (n_178));
  NOR2X1LVT g5411__2802(.A (n_67), .B (n_66), .Y (n_151));
  AOI22X1LVT g5423__5122(.A0 (\fifo_mem[5] [1]), .A1 (n_87), .B0
       (\fifo_mem[3] [1]), .B1 (n_291), .Y (n_65));
  AOI22X1LVT g5416__8246(.A0 (\fifo_mem[5] [0]), .A1 (n_87), .B0
       (\fifo_mem[3] [0]), .B1 (n_291), .Y (n_64));
  AOI22X1LVT g5417__7098(.A0 (\fifo_mem[5] [3]), .A1 (n_87), .B0
       (\fifo_mem[3] [3]), .B1 (n_291), .Y (n_63));
  AOI22X1LVT g5419__6131(.A0 (\fifo_mem[5] [11]), .A1 (n_87), .B0
       (\fifo_mem[3] [11]), .B1 (n_291), .Y (n_62));
  AOI22X1LVT g5422__1881(.A0 (\fifo_mem[4] [4]), .A1 (n_93), .B0
       (\fifo_mem[7] [4]), .B1 (n_94), .Y (n_61));
  AOI22X1LVT g5415__5115(.A0 (\fifo_mem[5] [10]), .A1 (n_87), .B0
       (\fifo_mem[3] [10]), .B1 (n_291), .Y (n_60));
  AOI22X1LVT g5425__7482(.A0 (\fifo_mem[5] [14]), .A1 (n_87), .B0
       (\fifo_mem[3] [14]), .B1 (n_291), .Y (n_59));
  AOI22X1LVT g5426__4733(.A0 (\fifo_mem[5] [13]), .A1 (n_87), .B0
       (\fifo_mem[3] [13]), .B1 (n_291), .Y (n_58));
  AOI22X1LVT g5427__6161(.A0 (\fifo_mem[4] [5]), .A1 (n_93), .B0
       (\fifo_mem[7] [5]), .B1 (n_94), .Y (n_57));
  AOI22X1LVT g5430__9315(.A0 (\fifo_mem[5] [15]), .A1 (n_87), .B0
       (\fifo_mem[3] [15]), .B1 (n_291), .Y (n_56));
  AOI22XLLVT g5392__2883(.A0 (\fifo_mem[1] [15]), .A1 (n_246), .B0
       (dout[15]), .B1 (n_267), .Y (n_55));
  AOI22X1LVT g5395__2346(.A0 (\fifo_mem[0] [3]), .A1 (n_244), .B0
       (\fifo_mem[2] [3]), .B1 (n_266), .Y (n_54));
  AOI22X1LVT g5396__1666(.A0 (\fifo_mem[2] [9]), .A1 (n_266), .B0
       (dout[9]), .B1 (n_267), .Y (n_53));
  AOI22XLLVT g5399__7410(.A0 (\fifo_mem[1] [6]), .A1 (n_246), .B0
       (dout[6]), .B1 (n_267), .Y (n_52));
  AOI22X1LVT g5400__6417(.A0 (\fifo_mem[2] [7]), .A1 (n_266), .B0
       (dout[7]), .B1 (n_267), .Y (n_51));
  AOI22X1LVT g5401__5477(.A0 (\fifo_mem[2] [0]), .A1 (n_266), .B0
       (dout[0]), .B1 (n_267), .Y (n_50));
  AOI22X1LVT g5402__2398(.A0 (\fifo_mem[0] [2]), .A1 (n_244), .B0
       (\fifo_mem[1] [2]), .B1 (n_246), .Y (n_49));
  AOI22X1LVT g5405__5107(.A0 (\fifo_mem[0] [8]), .A1 (n_244), .B0
       (\fifo_mem[1] [8]), .B1 (n_246), .Y (n_48));
  AOI22X1LVT g5414__6260(.A0 (\fifo_mem[2] [10]), .A1 (n_266), .B0
       (dout[10]), .B1 (n_267), .Y (n_47));
  AOI22X1LVT g5418__4319(.A0 (\fifo_mem[0] [4]), .A1 (n_244), .B0
       (\fifo_mem[1] [4]), .B1 (n_246), .Y (n_46));
  AOI22X1LVT g5420__8428(.A0 (\fifo_mem[0] [13]), .A1 (n_244), .B0
       (\fifo_mem[1] [13]), .B1 (n_246), .Y (n_45));
  AOI22X1LVT g5421__5526(.A0 (\fifo_mem[2] [12]), .A1 (n_266), .B0
       (dout[12]), .B1 (n_267), .Y (n_44));
  AOI22X1LVT g5424__6783(.A0 (\fifo_mem[2] [11]), .A1 (n_266), .B0
       (dout[11]), .B1 (n_267), .Y (n_43));
  AOI22XLLVT g5428__3680(.A0 (\fifo_mem[1] [1]), .A1 (n_246), .B0
       (dout[1]), .B1 (n_267), .Y (n_42));
  AOI22XLLVT g5429__1617(.A0 (\fifo_mem[1] [14]), .A1 (n_246), .B0
       (dout[14]), .B1 (n_267), .Y (n_41));
  AOI22X1LVT g5431__2802(.A0 (\fifo_mem[0] [5]), .A1 (n_244), .B0
       (\fifo_mem[1] [5]), .B1 (n_246), .Y (n_40));
  XNOR2X1LVT g5432__1705(.A (wptr[0]), .B (n_37), .Y (n_39));
  OAI22X1LVT g5433__5122(.A0 (n_17), .A1 (n_37), .B0 (n_36), .B1
       (n_33), .Y (n_38));
  MX2XLLVT g5434__8246(.A (n_13), .B (wptr[2]), .S0 (n_37), .Y (n_35));
  INVXLLVT g5436(.A (n_34), .Y (n_75));
  NAND3BXLLVT g5437__7098(.AN (wptr[2]), .B (rstn), .C (n_33), .Y
       (n_34));
  NAND3X1LVT g5435__6131(.A (wptr[2]), .B (rstn), .C (n_33), .Y (n_66));
  AND2X1LVT g5443__1881(.A (n_32), .B (rptr[0]), .Y (n_87));
  NOR2BX1LVT g5446__5115(.AN (n_32), .B (rptr[0]), .Y (n_93));
  NOR2X1LVT g5448__7482(.A (rptr[0]), .B (n_28), .Y (n_95));
  NOR2X1LVT g5444__4733(.A (n_22), .B (n_30), .Y (n_246));
  NOR2X1LVT g5447__6161(.A (rptr[0]), .B (n_24), .Y (n_266));
  OAI2BB1X1LVT g5456__9315(.A0N (rptr[1]), .A1N (n_267), .B0 (n_25), .Y
       (n_31));
  INVX1LVT g5438(.A (n_33), .Y (n_37));
  NOR2X1LVT g5445__9945(.A (rptr[0]), .B (n_30), .Y (n_244));
  NOR2X1LVT g5451__2883(.A (rptr[1]), .B (n_27), .Y (n_32));
  NOR2BX1LVT g5439__2346(.AN (wr_en), .B (full), .Y (n_33));
  OR2XLLVT g5455__1666(.A (n_20), .B (n_27), .Y (n_28));
  NOR2X1LVT g5453__7410(.A (n_26), .B (n_27), .Y (n_94));
  OAI211X1LVT g5463__5477(.A0 (rptr[0]), .A1 (rptr[1]), .B0 (n_26), .C0
       (n_21), .Y (n_25));
  NAND2X1LVT g5449__2398(.A (rptr[1]), .B (n_19), .Y (n_24));
  OAI22X1LVT g5457__5107(.A0 (rptr[0]), .A1 (n_267), .B0 (n_22), .B1
       (n_21), .Y (n_23));
  NAND2X1LVT g5450__6260(.A (n_20), .B (n_19), .Y (n_30));
  MX2XLLVT g5454__4319(.A (n_7), .B (rptr[2]), .S0 (n_267), .Y (n_18));
  AOI221X1LVT g5458__8428(.A0 (n_20), .A1 (n_8), .B0 (rptr[1]), .B1
       (n_17), .C0 (n_14), .Y (full));
  NAND2X1LVT g5461__5526(.A (rptr[2]), .B (n_21), .Y (n_27));
  NOR2X1LVT g5460__6783(.A (rptr[2]), .B (n_267), .Y (n_19));
  INVX1LVT g5464(.A (n_267), .Y (n_21));
  NAND2BX1LVT g5465__3680(.AN (empty), .B (rd_en), .Y (n_267));
  OAI211X1LVT g5462__1617(.A0 (n_10), .A1 (n_13), .B0 (n_12), .C0
       (n_11), .Y (n_14));
  NOR2XLLVT g5468__2802(.A (n_12), .B (n_9), .Y (empty));
  NAND2XLLVT g5467__1705(.A (n_10), .B (n_13), .Y (n_11));
  OAI221X1LVT g5469__5122(.A0 (wptr[1]), .A1 (n_20), .B0 (rptr[1]), .B1
       (n_36), .C0 (n_290), .Y (n_9));
  INVX1LVT g5471(.A (n_17), .Y (n_8));
  MXI2XLLVT g5466__8246(.A (rptr[2]), .B (n_10), .S0 (n_26), .Y (n_7));
  XNOR2X1LVT g5470__7098(.A (wptr[2]), .B (n_67), .Y (n_13));
  NOR2X1LVT g5472__6131(.A (n_6), .B (n_5), .Y (n_17));
  AOI22X1LVT g5474__5115(.A0 (n_1), .A1 (n_22), .B0 (wptr[0]), .B1
       (rptr[0]), .Y (n_12));
  NOR2X1LVT g5479__7482(.A (wptr[1]), .B (n_1), .Y (n_6));
  NOR2X1LVT g5480__4733(.A (wptr[0]), .B (n_36), .Y (n_5));
  NAND2X1LVT g5476__6161(.A (rptr[0]), .B (rptr[1]), .Y (n_26));
  NAND2X1LVT g5475__9315(.A (wptr[0]), .B (wptr[1]), .Y (n_67));
  MXI2XLLVT g2(.A (rptr[2]), .B (n_10), .S0 (wptr[2]), .Y (n_290));
  DFFRX1LVT \wptr_reg[0] (.RN (rstn), .CK (clk), .D (n_39), .Q
       (wptr[0]), .QN (n_1));
  DFFRX1LVT \rptr_reg[0] (.RN (rstn), .CK (clk), .D (n_23), .Q
       (rptr[0]), .QN (n_22));
  DFFRX1LVT \rptr_reg[2] (.RN (rstn), .CK (clk), .D (n_18), .Q
       (rptr[2]), .QN (n_10));
  DFFRX1LVT \rptr_reg[1] (.RN (rstn), .CK (clk), .D (n_31), .Q
       (rptr[1]), .QN (n_20));
  DFFRX1LVT \wptr_reg[1] (.RN (rstn), .CK (clk), .D (n_38), .Q
       (wptr[1]), .QN (n_36));
  NOR2BX1LVT g5647(.AN (n_19), .B (n_26), .Y (n_291));
  NOR2BX1LVT g5648(.AN (n_6), .B (n_66), .Y (n_292));
  NOR2BX1LVT g5649(.AN (n_5), .B (n_66), .Y (n_293));
endmodule

